### ISSUE TITLE
As a WOAQ contributor, I want to know how to visually style front-end components.

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#101]
**Is your feature request related to a problem? Please describe.**
The current contributing.md file contains a section titled "Style Guides." It does not yet reflect the latest decision to use default/out-of-box Foundation visual styles.

**Describe the solution you'd like**
Add a bullet item under "Style Guides" for "Visual/CSS styling: [Foundation 6 Global Styles](https://foundation.zurb.com/sites/docs/global.html)

**Describe alternatives you've considered**
Not including it (increases likelihood of rogue styles being implemented).

**Additional context**

### For Developers
**Affected Components**
[contributing.md](https://github.com/openoakland/woeip/blob/master/.github/contributing.md)

**Technical Resources**
n/a

**Design Documentation**
n/a

**Testing Outline**
Standard PR review.

**Comment by TangoYankee** [comment]
@theecrit Want to try your hand at making a pull request with these changes?

**Comment by theecrit** [comment]
@TangoYankee Yes! Will give it a shot tonight or tomorrow am. :)

**Comment by TangoYankee** [comment]
Related to closed issue  #92

**Comment by theecrit** [comment]
Closing w/ PR 103.
