### ISSUE TITLE
As a user, I'd like site pages to follow a consistent grid so it's easier to navigate.

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#104]
**Is your feature request related to a problem? Please describe.**
Currently, certain views (specifically "Add Data") do not conform to a grid layout that matches other views.

**Describe the solution you'd like**
For a Foundation-based grid to be applied to all views consistently as appropriate.

**Describe alternatives you've considered**
Non-grid based layouts introduce inconsistencies, introducing cognitive load for the user and making the site harder to use. 

**Additional context**
<img width="800" alt="Screen Shot 2019-05-14 at 4 54 16 PM" src="https://user-images.githubusercontent.com/32755410/57739593-08099480-7669-11e9-9281-2ef28b43d7b9.png">
<img width="800" alt="Screen Shot 2019-05-14 at 4 54 24 PM" src="https://user-images.githubusercontent.com/32755410/57739594-08a22b00-7669-11e9-8eef-86d1a306b01a.png">

### For Developers
**Affected Components**
TBD

**Technical Resources**
TBD

**Design Documentation**
TBD

**Testing Outline**
TBD

**Comment by TangoYankee** [comment]
`Add data`/`upload` is going to be completely restyled to match the wireframes. ie) Drag and Drop

**Comment by theecrit** [comment]
Yes; just want to make sure we use a grid consistently across the product. Not sure the best way to ensure that happens if/as we create new pages/views to the site.

**Comment by theecrit** [comment]
Closing as won't fix (given it will be part of applying visual styling later).
