### ISSUE TITLE
Fix contributing.md 

### ISSUE THREAD

**Issue by Ethan-bradley** [openoakland/woeip#107]
### Current scenario
Contributing.md is not quite accurate or complete, making it difficult to onboard new developers.

### Proposed solution(s)
- Restructure the page to include clear sections for: Overview, Running the build locally (Docker & local machine), Team workflow & standards (forks & branches, issues & projects, labels, style guides, etc)

- Additional changes to include in *Running the build locally* section (pending more detail from @Ethan-bradley):
  - On Contributing.md, the image for make local.shell should be fixed to look like it is not in the shell already.
  - Additionally, add go to http://0.0.0.0:8080/ to access the site and log in with those usernames and passwords. This should go below the ./manage.py.

**Comment by theecrit** [comment]
@Ethan-bradley A couple of questions:

1. What should replace the image for `./manage.py createsuperuser`?
2. Where should the `add go to http://0.0.0.0:8080/ to access...` bit be added?

I can take care of both of these tonight.

**Comment by theecrit** [comment]
Added some additional detail to the issue itself for clarity.

**Comment by Ethan-bradley** [comment]
Sorry for not adding more clarity earlier, here is the proposed solution:
That make local.shell shoud look like this:
![Screen Shot 2019-06-14 at 2 17 59 PM](https://user-images.githubusercontent.com/30478290/59538640-594ab500-8eaf-11e9-9901-45259daa7b32.png)
I think I made a mistake and referenced the ./manage.py instead of the make local.shell, I fixed that in the issue comment above. I can fix these problems tonight if needed.

**Comment by Ethan-bradley** [comment]
Additional lines under workflow that needs to be edited:
Maybe add that estimated time to setup everything (including installing docker) is around 30-45 minutes. 
Add Open terminal
Add Install git (May add instructions for git installation: https://docs.gitlab.com/ee/gitlab-basics/start-using-git.html) if not already installed. If you are on a mac, just type in git and hit ok to install software tools.  
Run the following commands in terminal:
Change git clone line to git clone https://github.com/openoakland/woeip.git, currently incorrect.
Separate the first two code lines to allow for easier copy and paste. 
Add go to 0.0.0.0:8080 on your web browser
Put in the username that you put in the terminal for the email.

**Comment by TangoYankee** [comment]
Many of the items in this list are issues for new developers in general. For a couple past projects, I have moved things like _open terminal_ and _install git_  to a **New developer guide** in the [woeip/wiki](https://github.com/openoakland/woeip/wiki). If it's something that is common to a lot of potential contributors, it may be worth finding an existing tutorial that we can incorporate. 

Alternatively, we can make it an OpenOakland project specifically to on-board new developers to git and the terminal. After all, git has (basically) become a prerequisite for contributing to open source projects.

Thinking of this in the context of helping new developers learn, throwing everything at them all once can feel overwhelming. However, we may be able to break down git and the terminal into manageable pieces that encourage people to stay engaged and see progress in their own personal development. Of course, this is an issue much larger than our **Contributing.md**

**Comment by theecrit** [comment]
I think the contributing.md should include the WOEIP-specific, step-by-step instructions for what it takes to get up and running. So that includes basics like opening terminal and running specific commands. 

For more basic instructions around general workflows (getting comfortable with terminal, git, etc.), we could create a gist that links to existing resources aimed at beginners. I'd recommend a gist over the wiki, only so that other brigades can repurpose it. In fact, it's very likely other brigades have already compiled similar collections. I'll start a Discourse thread to see what's out there and if it's worth collecting/curating them.

**Comment by ChenglimEar** [comment]
It looks like the login is with the username and not the e-mail that was set up with `createsuperuser`.  When updating the doc with a login step, it should be clear what to enter to login.  Perhaps this is a bug in the login code and we want it to work with the e-mail instead of the username?

**Comment by ChenglimEar** [comment]
It may be good to also update the test section and mention that `make test` will run the current set of tests.

**Comment by theecrit** [comment]
Fixed w/ PR114
