### ISSUE TITLE
Finalize a deployment workflow using woaq.org

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#116]
**Is your feature request related to a problem? Please describe.**
The current plan is to use woaq.org as the production domain for the time being, with the intention of having an easy-to-remember, standalone website accessible to the general public and credentialed users. 

Client prod domain on woaq.org corresponding to master branch
Client staging domain on branch_name.woaq.org corresponding to branch name

API prod domain on api.woaq.org corresponding to master branch
API staging domain on api.staging.woaq.org corresponding to active branch

**Describe the solution you'd like**
For now:
- [x] woaq.org redirects to GitHub repo

Future:
- [ ] woaq.org provides client interface from master branch
- [ ] branch_name.woaq.org allows for client preview of any branch
- [ ] api.woaq.org provides api access from master branch
- [ ] api.staging.woaq.org provides api access from current active branch
- [ ] AWS S3 bucket to store files

**Describe alternatives you've considered**
Unmerged branches existing only in local builds, making collaboration a bit more difficult.

**Additional context**
woaq.org is hosted on OpenOakland's AWS account, so changes need to be made via the Leadership team. Posting the request in #leadership on Slack nets a pretty quick response. @theecrit has access to AWS and may be able to assist.

### For Developers
**Affected Components**
- [ ] AWS

**Testing Outline**
TBD

**Comment by theecrit** [comment]
@ifed3 Feel free to edit anything in there and re-label accordingly. Thanks!

**Comment by TangoYankee** [comment]
[making sense of docker-compose overrides](https://medium.com/it-dead-inside/making-sense-of-docker-compose-overrides-efb757460d64)

**Comment by theecrit** [comment]
Might also be worth taking a look at how OpenOUSD handles staging and deployment: https://github.com/openoakland/openousd-site

**Comment by theecrit** [comment]
Won't fix.
