### ISSUE TITLE
[Improvement] Implement updated database schema

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#117]
**Is your feature request related to a problem? Please describe.**
Our current database model doesn't accommodate a number of dependencies and attributes that would allow it to scale as additional sensors/devices/data formats come into play. After much discussion, we've landed on a model that normalizes the data to what we feel is the right degree for where the project is now.

**Describe the solution you'd like**
We'd like to update the current database model by removing the older tables and replacing them with the new tables per the attached model diagram.

**Describe alternatives you've considered**
Leaving the model as-is and refactoring later, as the need arises. This adds technical debt in the future, rather than resolving some of those issues now.

**Additional context**
See: https://github.com/openoakland/woeip/issues/115

### For Developers
**Affected Components**
@ifed3 Can you add relevant links here?

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.
@ifed3 Can you add relevant info here?

**Design Documentation**
![WOEIP Schema V2 (2)](https://user-images.githubusercontent.com/32755410/60562079-e9d82080-9d0a-11e9-8f3d-d9c4ef9f487e.jpg)

**Testing Outline**
TBD

**Comment by nbilenko** [comment]
This work is in progress at this [remote branch](https://github.com/openoakland/woeip/tree/nb-database-update).
A few additions were made to the schema above, please comment if you have any feedback!
* `Calibration.calibrated_at: datetime`
* `Collection.route: string` (can be blank for now)
* `CollectionFile.url => CollectionFile.file` (using the FileField will take advantage of django file handling

Work planned for next week.
@kdoby and @nbilenko: adding tests to the models.
@r-b-g-b: re-adding the basic views (removed to make the models work).

**Comment by theecrit** [comment]
@nbilenko Looks good to me, thanks for the update!

Does this mean `Collection.route: string` requires a controlled vocab, and assumes a manual input from the user? (That would make sense to me, just want to ensure I address that dependency on the design side.)

**Comment by TangoYankee** [comment]
> @nbilenko Looks good to me, thanks for the update!
> 
> Does this mean `Collection.route: string` requires a controlled vocab, and assumes a manual input from the user? (That would make sense to me, just want to ensure I address that dependency on the design side.)

@theecrit I'm reviewing the code. It looks like the route is user-inputted, optional, and independent from other fields. There is no control to the vocab and no real system need to control it. SGTM.

**Comment by nbilenko** [comment]
Yes - we can add a controlled vocab later on, but for now this leaves route as an optional freetext field.
