### ISSUE TITLE
As a data contributor, I want to store raw data sets safely in one place so their data can be used by the system

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#130]
**Description**
Currently, a WOEIP AQ data collection session (named collection in the database) is represented by a pair of CSV and GPS log files.  We want to store all files on a single cloud-based server in a way that is easily accessible to the system (ultimately designing the system so they’re accessible to WOEIP staff). 

**Acceptance criteria**
- [x] ~S3 destination directory set up on AWS.~
- [ ] Service comparison has been completed and discussed with WOEIP
- [ ] Appropriate service has been selected and accounts created
- [ ] Directory is accessible to the API for data extraction purposes.
- [ ] All open questions in Issue have been answered or moved into new Issues.

**Dependencies and assumptions**
- User must be authenticated (signed in). 
- Once uploaded, files must be maintained in a raw, unadulterated format permanently (for data integrity/checks and balances).
- Directory considerations require security, and low storage costs. 

**Related documentation**
- [Service Hosting Comparison worksheet](https://docs.google.com/spreadsheets/d/1kPY3JD0S077_kXkl7GDN6PG0EHTLhFBp6HoMt1gBgC8/edit?usp=sharing)
- [WOAQ-data-flow-diagram-v5](https://drive.google.com/open?id=1oCfbhN_KG6E-0KgR9B6o9j1OOTmS9StO)
- [Instructions for requesting S3 bucket from CfA](http://brigade.codeforamerica.org/resources/software/aws)
- [Amazon AWS Pricing](https://aws.amazon.com/s3/pricing/)

**Open questions**
- [x] What is the name of the destination directory?
- [ ] System checks can be done either client-side via javascript or server-side. Considerations include security, speed, load capacity, and development team’s capabilities. Options we’re exploring:
-- [ ] Hold uploaded data in temporary pandas.DataFrame.
-- [ ] Hold uploaded data in temp. staging table.
-- [ ] Move data directly into main table marked with "unvalidated" flag.

**Comment by theecrit** [comment]
Current estimate is <1GB data storage for MVP.

**Comment by theecrit** [comment]
@r-b-g-b @nbilenko Created **open-oakland-woaq**, but I'm now thinking we should store raw data files separately from any other objects that may end up here, and that it should be named semantically to be really clear (i.e. **open-oakland-woaq-raw-data-archives**). Thoughts?

Also, I think we should move the following section of the issue to a dedicated ticket:

>  System checks can be done either client-side via javascript or server-side. Considerations include security, speed, load capacity, and development team’s capabilities. Options we’re exploring:
> -- [ ] Hold uploaded data in temporary pandas.DataFrame.
> -- [ ] Hold uploaded data in temp. staging table.
> -- [ ] Move data directly into main table marked with "unvalidated" flag.

**Comment by theecrit** [comment]
I'm going to compile hosting comparison of following:
- Cost
- Server memory
- Tech stack support
- Ethics
- Tech support
- UI ease
- Security
- Uptime
- etc

Will look at:
- MS Azure
- Amazon AWS
- Dreamhost
- Heroku
- Digital Ocean
- On-premise server
- etc

Then we'll review as a team and bring an informed opinion to WOEIP.

**Comment by TangoYankee** [comment]
@theecrit Per our discussion, WOEIP already has a [Dreamhost](https://www.dreamhost.com/) account. To keep accounts consolidated, we would like to stick with Dreamhost. Because Dreamhost shared machines do not [support](https://help.dreamhost.com/hc/en-us/articles/217141627-Supported-and-unsupported-technologies) our tech stack, we are looking to have a [dedicated machine](https://www.dreamhost.com/hosting/dedicated/).

**Comment by theecrit** [comment]
@TangoYankee Which component of our tech stack doesn't DreamHost support?

**Comment by theecrit** [comment]
Per team conversation on 8/4/2020, I'll run AWS by Brian and see if he'd prefer a more thorough evaluation via [this spreadsheet](https://docs.google.com/spreadsheets/d/1kPY3JD0S077_kXkl7GDN6PG0EHTLhFBp6HoMt1gBgC8/edit?usp=sharing).

**Comment by theecrit** [comment]
Closing as we're moving to Digital Ocean.
