### ISSUE TITLE
As a user, I want to understand if the files I uploaded aren't correct in some way

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#131]
## Description
I would like the system to display visual feedback in real time that informs me if I've uploaded the wrong file type, too many files, etc—and how to correct the issue.

## Acceptance criteria
- [ ] Once user initiates upload, visual indicator remains in motion while upload is in progress.
  - [ ] API Upload endpoint: see #145 and #146
- [ ] If files are successfully uploaded, system displays a success banner on the Data Confirmation view.
  - [ ] API: success state on 200 status
- [ ] If file upload fails, system displays an appropriate error banner on the File Upload view.
  - [ ] *API end points needed*
- [ ] All banners push page content down, rather than obscuring content.
- [ ] Accessibility features have been included in code:
  - [ ] Error and warning banners have a role=”alert” (so they’re announced by assistive tech)
  - [ ] All other banners have a role=”status” to be read after critical alerts
  - [ ] All banners have an aria-live attribute
  - [ ] Banners use aria-describedby to describe their purpose to assistive technologies when they’re announced or receive focus (description = banner text per wireframe)
- [ ] All open questions in Issue have been answered or moved into new Issues.

## Dependencies and assumptions
- ~Sequencing order has been identified~ See: [Flow Diagram](https://github.com/openoakland/woeip/files/4172627/WOAQ-Data-Flow-Diagram-v5.pdf)
- Errors display on File Upload view in order to provide real-time feedback to user, per wires/prototypes below.
- Success displays on Data Confirmation view to reinforce transition to next step per wires/prototypes below.
- Message copy maintains consistent voice and style.
- Visual design maintains consistent styles

## Related documentation
- [Latest wires are v6](https://www.figma.com/proto/IZw8VvX1CsRc764CTvg4aRSU/WOAQ-Wireframes-Parent-File?node-id=341%3A5663&scaling=contain) (v5 versions can be run as prototype to see flow)
- [Prototype: error path example](https://www.figma.com/proto/IZw8VvX1CsRc764CTvg4aRSU/WOAQ-Wireframes-Parent-File?node-id=341%3A5663&scaling=contain)
- [WOAQ-Data-Flow-Diagram-v5.pdf](https://github.com/openoakland/woeip/files/4157171/WOAQ-Data-Flow-Diagram-v5.pdf)
- [WOAQ-Upload-v5-Wireframes.pdf](https://github.com/openoakland/woeip/files/3937173/WOAQ-Upload-v5-Wireframes.pdf) (under discussion)
- ~[WOAQ-Upload-v4](https://drive.google.com/open?id=1Al5ILibeITvFcentrr0ia9R5QLRs9pIq)~

## Open questions
- [ ] Need to define “success” (e.g. rote file upload vs. data validation)
- [ ] Need to confirm the following API end points: generic error, too many files, one file only, two CSVs or two logs, no date match

**Comment by theecrit** [comment]
Added new v5 wires and revised acceptance criteria to reflect them. Once approved, we can change label from "needs definition" to "ready" and move it into the *Prioritized & Ready to Work On* column.

**Comment by theecrit** [comment]
Added prototypes and clarified description slightly.

**Comment by theecrit** [comment]
@joshling1919 @jayqi Does it make sense to assign this to one of you and move it into "In Progress"? (I don't recall who was specifically working on confirmations.) This has some accessibility requirements that might be worth a review, too.

**Comment by joshling1919** [comment]
@theecrit I think the the PR (https://github.com/openoakland/woeip/pull/214) that @TangoYankee is working on addresses this issue!
