### ISSUE TITLE
As a user, I want to locate and navigate to a specific session map

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#133]
## Description
The current assumption is that a user will be redirected to the map view of the data set they just uploaded from the Data Confirmation view. This doesn’t account for other uses cases:
As a data contributor, I want to view a specific data set I uploaded previously.
As a site visitor, I want to view a specific data set someone else uploaded.

## Acceptance criteria
- [ ] There’s an affordance for navigating to a specific session map ~~via global nav menu.~~ This can be achieved using the method described in issue #239 . Ie) First query `api.[domain]/collection?start_date=[yyyy-mm-dd]` (implemented). Then query `api.[domain]/collection{id}/data` (implemented) -TY
- [ ] ~~There’s an affordance for navigating to a specific session map from the Data Confirmation view.~~ Not necessarily required -TY
- [ ] All open questions in issue answered/documented.

## Dependencies
- Assumes Session Map (individual map) view is already implemented.
- Assumes View Maps (map index) view is already implemented.

## Related documentation
TBD

## Open questions
TBD

**Comment by TangoYankee** [comment]
@theecrit After discussing it, @Ajay-Vishwanath and I would like there to be two options. If a user navigates via the upload functionality, the user will see the session they just uploaded. If they navigate via the global bar, the user will see the most recently uploaded session date. In either case, user can select different session from within page.
