### ISSUE TITLE
As a user, I’d like to be able to view a list of all available session maps in one place

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#134]
## Description
We want any user to be able to navigate to a view of all the maps, sorted by date.

## Acceptance criteria
- [ ] Clicking on a link in the global nav loads a view of all maps on an ordered grid.
- [ ] View is accessible to all users (authenticated and unauthenticated).
- [ ] Maps are arranged in reverse chronological order.
- [ ] Maps are organized by month.
- [ ] Grid displays map thumbnail image that reflects the actual map, with date as caption (not currently reflected in wireframe; Mon DD, YYYY format).
- [ ] All open questions in Issue have been answered or moved into new Issues.

## Dependencies and assumptions
Requires individual session maps to be implemented.
Prefer endless scroll to paginated view but not a requirement.

## Related documentation
Wireframe: [WOAQ-ViewMaps-Option2-v1](https://drive.google.com/open?id=1RItnccLJz9WGmpMiNJn5CcxkECCVNFmW)

## Open questions
TBD

**Comment by TangoYankee** [comment]
The functionality will be replaced by a drop down menu to select a day of interest.
