### ISSUE TITLE
As a user, I’d like to be able to navigate from one session map to another

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#135]
## Description
When I’m viewing a map from a particular session, I want to be able to view the map before or after it chronologically.

## Acceptance criteria
- [ ] "View a different day" date picker implemented per wire.
- [ ] "Other sessions from today" implemented per wire (only displays on days with multiple sessions).
- [ ] All open questions in Issue have been answered or moved into new Issues.

## Dependencies and assumptions
- Requires View Maps be implemented.
- Team review of UX should be completed.
- Requires system can identify session sequence for multiple sessions per day.
- Requires completion of #159 

## Related documentation
Wireframe: [WOAQ-Wires-ViewMaps-v2.pdf](https://drive.google.com/open?id=1kP2MIls9wsYGffVQS1F-9gQolBWv_YO2)

## Open questions
TBD

**Comment by theecrit** [comment]
Requires completion of #159.

**Comment by TangoYankee** [comment]
In the listed wireframes, only the bottom view may be needed.

**Comment by theecrit** [comment]
Agreed, I think we can close this.
