### ISSUE TITLE
When there is more than one mobile session collected on a single day, I want to know which one I’m viewing

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#136]
## Description
In some cases, there will be multiple mobile sessions collected on any given day. When I’m viewing any of these sessions, I want to understand where the current one I’m viewing is in the sequence. Additionally, when the system displays a multiple sessions (e.g. in a grid or list view), it should display them in correct reverse chronological order. This requires each session to have a sequence attribute.

## Acceptance criteria
- [x] Database’s Collection entity has a Sequence attribute formatted as an integer.
- [x] *Sequence* attribute corresponds to the chronological order of all sessions collected within that calendar day.
- [ ] Sequence defines the display order of all maps.
- [ ] All open questions in Issue have been answered or moved into new Issues.

## Dependencies
Database entities are adjusted to accommodate above attributes.

## Related documentation
Wireframe: [WOAQ-Wires-ViewMaps-v2.pdf](https://drive.google.com/open?id=1kP2MIls9wsYGffVQS1F-9gQolBWv_YO2)

## Open questions
TBD

**Comment by theecrit** [comment]
@nbilenko I'm wondering if this should be deleted, based on my Q in PR140:

> Sequence is appended to sessionName when displaying in the View Maps UI.

**Comment by nbilenko** [comment]
> @nbilenko I'm wondering if this should be deleted, based on my Q in PR140:
> 
> > Sequence is appended to sessionName when displaying in the View Maps UI.

That'll be a front-end issue - PR140 addresses the backend capability for providing the sequence number.

Question re: 
> Sequence is displayed where relevant in the Upload UI (particularly with regards to the metadata confirmation view).

Is this needed? We discussed that if the user isn't uploading the sessions in order, this might be confusing. Additionally, this would be technically challenging - the data isn't yet saved to the database during the metadata verification step, and so the sequence number won't be yet available.

**Comment by theecrit** [comment]
Yeah, I think you're right — I'll remove those, and if we discover during MVP testing that the user needs affordance for sequence in the upload flow, we can revisit. I do think it matters in the View Maps view, but PR140 enables the backend functionality for that.

**Comment by nbilenko** [comment]
Sequence is now exposed as an API call `/collection/<id>/sequence` via https://github.com/openoakland/woeip/pull/152

**Comment by theecrit** [comment]
@nbilenko Can we safely close this, given #152 is now merged? These criteria are still open, so I'm not clear if there's more work to be done:

>  Sequence defines the display order of all maps.
> All open questions in Issue have been answered or moved into new Issues.

**Comment by nbilenko** [comment]
#152 completed the backend part of this issue, but I didn't close this since the frontend hasn't been implemented yet. I'd alternatively be fine with closing the issue and having a new issue for the frontend (that separation would probably make sense in general) - what do you think @theecrit?

**Comment by theecrit** [comment]
@nbilenko Yeah, since the front-end piece has a dependency on the View Session Map view, I think we should close this and address the front-end display as part of a single issue addressing the various session metadata components we want to display next to a session map (see #156).
