### ISSUE TITLE
As a developer, I want to know how to use the API

### ISSUE THREAD

**Issue by r-b-g-b** [openoakland/woeip#148]
## Description
We should make it easy to find documentation containing the input and output format for each API endpoint. We'd like it to be automatically generated from code to minimize manual upkeep work. 

## Acceptance criteria
- [ ] Input/output format for each API is clearly documented in one location (either this repo's wiki, or a Google Doc in the [*WOAQ > Engineering* folder](https://drive.google.com/open?id=1Ohfe1fGzTaHamw0cYSoXmJSTbhnHOV6V).
- [ ] System is built so the documentation gets updated automatically when the API code gets updated.
- [ ] Code passes any relevant tests needed.

## Relevant documentation
- [Django rest framework documentation](https://www.django-rest-framework.org/topics/documenting-your-api/) mentions [Swagger UI](https://swagger.io/tools/swagger-ui/) and [ReDoc](https://github.com/Rebilly/ReDoc).

**Comment by jayqi** [comment]
This appears to be currently-maintained main way people autogenerate API documentation for Django REST Framework. 

https://github.com/axnsan12/drf-yasg

The readme makes it seem like it should be reasonably straightforward to implement.

**Comment by jayqi** [comment]
I'm taking a crack at this right now.
