### ISSUE TITLE
As a user, I want to know certain details about the session whose map I'm viewing.

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#156]
## Description
Issue #159 creates the ability to view a single session's data on a map. As a user viewing this map, I'd like to be able to see additional info about the session alongside the map itself. 

## Acceptance criteria
- [ ] Metadata appears alongside map in a single view. This issue covers only the following metadata items:
 - [x] Session date
 - [x] Session sequence number (see #136; need not display if there's only 1 session from the selected date)
 - [x] Other sessions from today
 - [x] Start time
 - [ ] Device model
 - [x] Link to raw data 

## Documentation
- Wireframe: [WOAQ-Wires-ViewMaps-v2.pdf, p4](https://drive.google.com/open?id=1kP2MIls9wsYGffVQS1F-9gQolBWv_YO2)

## Dependencies and assumptions
- Map view is already created (issue #159 complete).
- An additional issue will be created for session date picker and collector's name.

## Additional reference
Note: our partner's Truck Tracker app from @motching has a similar UI, so it's probably worth checking out that code to see if we can adapt it, rather than reinvent the wheel: https://github.com/woeip

**Comment by theecrit** [comment]
@Ajay-Vishwanath Hello! I'm going to close this issue as complete and open new ones for "Device" and "Collected by" fields.

**Comment by Ajay-Vishwanath** [comment]
@theecrit Sounds great, makes sense!
