### ISSUE TITLE
Use Session as foreign key to Data

### ISSUE THREAD

**Issue by r-b-g-b** [openoakland/woeip#16]
A key design consideration for the database was to have each sample in a separate row of the ``Data`` table. An hour session sampled at 1 Hz would have 3600 rows then. 1000 of those sessions would need 3,600,000 rows. To avoid getting too big ``Data`` shouldn't have too many columns. It should also probably not have any many-to-many fields, since they would lead to very large [bridging tables](https://dzone.com/articles/how-to-handle-a-many-to-many-relationship-in-datab). Currently, ``Data`` is very lean: aside from the essential ``lat``, ``lon``, ``time``, and ``value`` fields, it only has a single additional foreign key column to link it to the rest of the database, the ``SessionData`` model. ``SessionData`` contains the raw data file.

But ``Data`` rows can result from two raw data files -- e.g., air quality data coming from the Dustrak csv and the GPS location coming from a separate GPS log. My imperfect solution was to only link each ``Data`` row to the air quality measurement ``SessionData``, conveniently forgetting about the GPS raw data file. Not great. Of course, you could always query other ``SessionData`` from that ``Session`` to find it, but this isn't perfect either, since there could be other unrelated ``SessionData`` entries.

@nbilenko made a suggestion that I hadn't considered, which is to use ``Session`` as the foreign key to ``Data``. Now the database relationship looks like this:

```
Session A --------Data (lat=123.2943, lon=37.1334, value=0.3, session="Session A")
           \------SessionData (upload=dustrak.csv, sensor=<an air quality sensor>, session="Session A") 
            \-----SessionData (upload=gps.log, sensor=<a gps sensor>, session="Session A")
```

This will mean that a separate ``Session`` should exist for each "stream" of data. That is, if a participant walks around collecting two kinds of air quality measurements simultaneously, they will need to make two separate ``Session`` entries, which I think is fine.

**Comment by clintonb** [comment]
What problem are you trying to solve? 3.6M rose is not a lot of data in the grand scheme of things. Data issues will be a nice problem to have, but it’s not a problem that exists today. 

The new schema also makes it impossible to know which data file is linked to a specific datum.

**Comment by r-b-g-b** [comment]
The problem is that we do not make explicit where each field of ``Data`` comes from. For any given row of ``Data``, we see that it is linked to the ``SessionData`` for the Dustrak raw data file, let's call it ``dustrak1.csv``. But the assumption is that all fields of that ``Data`` row come from ``dustrak1.csv``, which is not true. Only the ``value`` field does; the ``lat`` and ``lon`` come from another file, let's call it ``gps1.log``. We have no way of knowing that (unless we know to look for other ``SessionData``s sharing the ``Session``.

The proposed solution is not perfect, but it gets closer. By linking the ``Data`` to ``Session``, we know that a row of ``Data`` was made by somehow combining the ``SessionData`` entries linked to that ``Session``. It's more vague, but it reflects the vagueness of the reality, that there's some fuzzy process that goes from raw data to processed ``Data`` rows.

It also opens up the possibility of making a new model ``DustrakSession`` that subclasses ``Session`` and has labeled ``gps`` and ``dustrak`` file fields.

**Comment by clintonb** [comment]
Ah. I agree with replacing `SessionData` with `Session`.

I wouldn't worry too much at this stage about knowing exactly which file created which field given it's obvious at this stage.
