### ISSUE TITLE
When I upload a data set, I want the system to automatically check for duplicates

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#176]
**Is your feature request related to a problem? Please describe.**
There may be cases when a volunteer accidentally tries to upload data that's already been uploaded. This would cause duplicate data to be added to the database, which would increase resource load unnecessarily and may pose issues with data cleanliness.

**Describe the solution you'd like**
There should be a way for the system to recognize when this happens and flag it for the user.

**Open questions**
* [ ] Should the system allow the user to override the existing data set with the new one, or should it simply report that the action can't be completed and state the reason?
* [ ] If so, should the system keep track of versions (and if so, should it allow reversion)? *If yes, we should create a design ticket for what this flow should look like before implementing.*

### Whoever picks up this issue, please complete:
**Affected Components**
List what pages or backend files will need to be added, removed, or changed

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
Wireframes or other design resources

**Testing Outline**
Describe the testing methods appropriate for this feature

**Comment by theecrit** [comment]
@TangoYankee I'd like to nominate this for inclusion in MVP, given the potential for trouble in the database if it's punted.

**Comment by TangoYankee** [comment]
Oh, it could be a lot of fun! #hashing

**Comment by theecrit** [comment]
@wendy-wm-wu @sribbleinc Is this work complete? I don't see an open PR but I feel like I remember this being addressed.

**Comment by wendy-wm-wu** [comment]
@theecrit Yes, this is complete
