### ISSUE TITLE
Standardize and document latitude, longitude coordinate format

### ISSUE THREAD

**Issue by jayqi** [openoakland/woeip#187]
Currently there is not clear documentation and guardrails on lattitude, longitude coordinate ordering.

- The `python manage.py generate_data` script currently uses `(lat, lon)`.
- Dustrak parsing does `(lon, lat)`
  - https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/dustrak.py#L265

The more common standard is to do `(lon, lat)` to be equivalent to `(x, y)`.

- The Django `PointField` which we are using names their fields `x, y`
  - https://docs.djangoproject.com/en/3.0/ref/contrib/gis/geos/#django.contrib.gis.geos.Point
- GeoJSON uses `(lon, lat)`:
  - https://tools.ietf.org/html/rfc7946#section-3.1.1

If we agree on the `(lon, lat)` standard, we need to fix `python manage.py generate_data` and document clearly.

**Comment by jayqi** [comment]
To fix `python manage.py generate_data`:

The main script is here: https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/management/commands/generate_data.py

But it uses factories to create the objects here: https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/tests/factories.py

**Comment by TangoYankee** [comment]
GeoJSON [RFC 7946 spec](https://tools.ietf.org/html/rfc7946)

While Django does not seem opintionated on Point (x, y) being (lon, lat), [PostGIS](https://postgis.net/docs/ST_Point.html) is.

Dustrak.py follows this when saving the point to the database. However, it often flips the order when documenting and organizing the code. 

To help ease this confusion, I'd like to update this ordering. It won't change the logic of the code. However, it will help when reading and thinking about coordinates to always see them mentioned in the same order. 

Strategy:
- [x] Address immediate bug in west_oakland_geo_point line 33 [`return Point(lat, lon)`](https://github.com/openoakland/woeip/blob/fd8c1c68c039ca50f4b17a741b339ccca6aa96f3/api/woeip/apps/air_quality/tests/factories.py#L33) as it applies to generate fake data
- [x] Review backend code base for additional long/lat ordering issues
      - dustrak.py
      - models.py

- [ ] Adjust Contributing Document to reflect agreement on Long/Lat.
