### ISSUE TITLE
Front end tests: memory issues, config warnings, and reference errors

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#196]
1. Memory Issue
    - From running `npm test`
    - `Error: watch /home/millertim108/woeip/web ENOSPC`
    - ENOSPC -> no space left on device
    - Another warning associated with the error `--watch is not supported without git/hg, please use --watchAll `
    - Investigating that error brought me to this [Create-React-App-Typescript Issue](https://github.com/wmonk/create-react-app-typescript/issues/282). 
    - This led me to line 32 of `node_modules/razzle/scripts/test`. It will watch tests that are not run by a CI or using coverage. I considered changing `--watch` to `--watchAll`. They may have solved one of the messages but I doubt it would resolve the error issue. The bigger problem is that changing an external module... that is also git-ignored... is dangerous and impractical.
   - Proposed solution is... to run coverage! It turns off the watching that threatens memory. It also allows us to track the coverage reports in CI, the same way we track the backend.
  - **Update:** adding a -watchAll flag in package.json works, too. I still prefer a --coverage flag.

2. Config Warning
   - From running `npm test` or `jest`
   - Warning `ts-jest[main] (WARN) Replace any occurrences of "ts-jest/dist/preprocessor.js" or  "<rootDir>/node_modules/ts-jest/preprocessor.js" in the 'transform' section of your Jest confi
g with just "ts-jest"`
   - Proposed solution... heed the warning!

3. Reference errors
   - From running `npm test` or `jest`
   - `Cannot find module 'routes' from 'App.tsx'`
   - There is also a reference to the Map component in the index file
   - The running application seems to find the references find. It's the tests that are baffled. 
   - ~~I think the easiest solution is to write the whole relative path, rather than the abbreviated versions.~~  
**Update:** @joshling1919 implemented [moduleNameMapper](https://github.com/openoakland/woeip/blob/fe30796446019aea786964a7b0bdf915390d7bec/web/package.json#L62) in an upcoming change. This appears to be a more scalable solution as changing file paths only requires updating one reference.  
**Second Update**: For TSLint, it doesn't seem to recognize both `dev` and `an array of whitelisted modules`  in [`no-implicit-dependencies`](https://palantir.github.io/tslint/rules/no-implicit-dependencies/). Consequently, my vote has switched back to writing relative paths.  

4. Linting Automatically
  - `tslint --project .`
  - `npm run lint`

**Comment by joshling1919** [comment]
@TangoYankee looks like we can pass in "dev" and "whitelisted modules" to resolve the TSLint errors. Since we've now resolved aliases with tslint and testing, let's stay with aliased paths for now since it can make refactoring a lot more straightforward (especially since we seem to have to import `styled` from 'src/theme` pretty often).
