### ISSUE TITLE
file page

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#20]
### Description
Create a file page where users upload dustrak and gps data files, which are joined together and saved.

### Pieces:
- A form which accepts
    * dustrak file
    * gps file
    * user data
- A url which holds the path to the upload page
- Templates
   * A base template that holds the meta, head, and body tags
   * An upload template which interfaces with the form
- A view to hold the logic for the file page
- Authentication, to prevent everyone from uploading a file
- An indication of whether a user is authenticated
- Messages
  * Successful upload
  * Access denied
  * Failure to upload

### Note
We do not need a home page or a login screen. For now, users can manage their accounts and logins through the Django Admin page. Also, there can be a simple indicator on the page as to whether the user is authenticated.

**Comment by TangoYankee** [comment]
This might actually be two (or more) tasks. 
1. The structure of the url, html, and authentication
2. The logic, execution, and feedback of uploading a file

**Comment by r-b-g-b** [comment]
Thanks Tim! How do we do "Authentication, to prevent everyone from uploading a file" without a login screen?

**Comment by TangoYankee** [comment]
At this stage, we do have a login screen: http://localhost:8080/admin/

**Comment by clintonb** [comment]
The admin site is probably not what you want to use for non-admin users. Consider using an existing solution, like https://www.intenct.nl/projects/django-allauth/, to help with authentication for end users.

**Comment by TangoYankee** [comment]
Thank you for the resource, @clintonb . I will explore it more depth, for future tasks. To clarify, I have zero intention of using the admin screen in the MVP. However, it is a good pre-built component to use in development. By using it for now, we can focus on the mechanics of allowing an authenticated user to upload two files.

**Comment by r-b-g-b** [comment]
Note: within the view files should be converted to utf-8 encoding using ``django.utils.encoding.force_text``. The ``woeip.apps.air_quality.dustrak.join`` function expects file handles open in text mode.

**Comment by r-b-g-b** [comment]
Also: we should implement the database schema change suggested in #16 prior to making the upload form.

**Comment by TangoYankee** [comment]
[Validate User Permissions](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication)
[`Index` typically preferred over `home`](https://www.lifewire.com/index-html-page-3466505)
[Template naming and structuring conventions](https://oncampus.oberlin.edu/webteam/2012/09/architecture-django-templates)

**Comment by TangoYankee** [comment]
Closing this issue. It is too large on its own. Instead, it has been decomposed into separate problems that are tracked in open GitHub issues.
