### ISSUE TITLE
Un-nest the files object  

### ISSUE THREAD

**Issue by joshling1919** [openoakland/woeip#205]
**Is your feature request related to a problem? Please describe.**
It's currently kind of difficult to upload the collection files due to how the API endpoint expects the file to be nested under an object. Here's a good example of how the API currently expects the data to come in:

https://github.com/openoakland/woeip/blob/edf2a65706ede90733d51305cfd1b29f66795568/api/woeip/apps/air_quality/tests/test_api.py#L113

To send files, I used the [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) interface. The problem is that whenever I nested the file objects, then when it hit the API, because of the way it was serialized, it was no longer File objects.

**Describe the solution you'd like**
There might have been a way to do this, but after wrangling with it for a little over an hour, I gave up and edited the API to not nest the files.

**Describe alternatives you've considered**
We could perhaps set up some way to properly deserialize, but that solution would also involve changes to the API. There might be the correct way to serialize the data on the front end so that when it reaches the API, the nested file is still a File.

**Additional context**
This is a screenshot of what the proposed changes looks like:
![image](https://user-images.githubusercontent.com/18567829/80558777-57d38f80-8990-11ea-89fd-6eb233b7672e.png)

**Labels**
- [x] Add a status label
  - `discussing`
  - `ready`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
List what pages or backend files will need to be added, removed, or changed
https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/serializers.py
https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/tests/test_api.py

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
Wireframes or other design resources

**Testing Outline**
Describe the testing methods appropriate for this feature

**Comment by TangoYankee** [comment]
Related: #154

**Comment by TangoYankee** [comment]
~~I would prefer the post request to match what the API already expects. Changing the endpoints may lead to additional changes needed downstream in the API. However, I understand the diminishing returns of chasing the post request.~~

Nah, you right. All the documentation and best practices for FormData indicates that the files should all be on the top level.

Though, I do think looking for `dustrak` or `gps` in the filename is too fragile and inefficient. As we're changing the API anyway, could we instead set the key equal to the file type? ie)
```
for (const file of files) {
      let fileType: string = file.name.split('.').pop()!
      formData.append(fileType, file)
    }
```

**Comment by joshling1919** [comment]
> ~I would prefer the post request to match what the API already expects. Changing the endpoints may lead to additional changes needed downstream in the API. However, I understand the diminishing returns of chasing the post request.~
> 
> Nah, you right. All the documentation and best practices for FormData indicates that the files should all be on the top level.
> 
> Though, I do think looking for `dustrak` or `gps` in the filename is too fragile and inefficient. As we're changing the API anyway, could we instead set the key equal to the file type? ie)
> 
> ```
> for (const file of files) {
>       let fileType: string = file.name.split('.').pop()!
>       formData.append(fileType, file)
>     }
> ```

sure thing! btw, is there an easy way to test django locally?

**Comment by TangoYankee** [comment]
Will this do? [Testing](https://github.com/openoakland/woeip/blob/master/.github/contributing.md#testing)

**Comment by TangoYankee** [comment]
Looking at the API after hitting it with files from the front-end, it appears that the `collection_file` fields are filled. Meanwhile, the `upload_file` fields are missed. It seems the back-end tests are passing because they hit the API with a JSON object, rather than a Form.

**Comment by theecrit** [comment]
Closing; merged.
