### ISSUE TITLE
Date & Time validation utility in front end for upload function

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#208]
**Is your feature request related to a problem? Please describe.**
Delegated from Issue #132.
The API will only accept hits to the collections endpoint that have all the required fields, including start and end time. The front end is also expected to check whether the times from both files match.

**Describe the solution you'd like**
I would like functions in the front end that partially parse the gps and dustrak files to determine their start and end times. The GPS parser could look for the $GPRMC timestamp. As discussed below, we may only need the first timestamp for the GPS file. The Dustrak file could look for the Test Start Time/Date and Test Length fields. The check would be that they are with ~~10~~ two minutes of each other. 

**Describe alternatives you've considered**
We could check for dates and times listed in the file names. However, file names can be easily changed and broken. We could generate the time based on the current time. However, the current time may not have a string relationship with the time of colllection.

**Additional context**
Parsing these files will make the front end more bespoke to dustrak and gps files, making it less flexible to other file formats. However, it will make the experience more fluid and automatic within this use case.

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
Most likely a utility ts file in the Upload Folder.

**Technical Resources**
There should probably two separate functions. Each function takes its respective file and return the required times or errors. Dustrak returns an object with a start and end time. GPS returns a start time.

This may be split into Two PRs.

Possible use of [Moment.js](https://momentjs.com/docs/)

**Design Documentation**
- [Database Schema as of 4/30/2020](https://user-images.githubusercontent.com/32755410/80737017-cb2bed00-8ac7-11ea-9282-5836501a5fb6.png)
- [Wireframes](https://www.figma.com/file/IZw8VvX1CsRc764CTvg4aRSU/WOAQ-Wireframes-Parent-File?node-id=340%3A5671l)

**Testing Outline**
Each function should test a success and an error path. There are testing files in the backend: [dustrak](https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/tests/data/dustrak.csv) & [gps](https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/tests/data/gps.log)

**Comment by theecrit** [comment]
(Attached the database schema to the issue above.)

I think this was the intended solution when we initially discussed the definition of a session, though we didn't define the time window for matching. I think 10 minutes is too long based on the use case. Data collectors turn both devices on at approximately the same time, and I think a 2-minute window may be more realistic. Then we can extract earliest matching timestamp for _Start_ and last matching timestamp for _End_.

**Comment by TangoYankee** [comment]
> Then we can extract earliest matching timestamp for Start and last matching timestamp for End

Depends on the file. 
- The [GPS file](https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/tests/data/gps.log) lists timestamps for each geo point taken. They're in the lines marked [ $GPRMC](http://aprs.gids.nl/nmea/#rmc). 
- The [dustrak file](https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/tests/data/dustrak.csv) only lists the time once and then gives an end time.

My intent is to avoid parsing the whole files. That can be time expensive to code and also execute. I would rather save time by only looking at the header of the dustrak file to get the Start and End Time values. For the GPS file, we only really need the first time stamp. This would be to validate that it's in the correct window, rather than to be used in the upload form.

 > 2-minute window  

Sure!

**Comment by theecrit** [comment]
I see; that makes sense to me. As far as this being bespoke to these particular files, I think it's worth worrying about that once we're in a position to ingest other data.

The most likely "next data type" to ingest will be Truck Tracker data, just FYI.
