### ISSUE TITLE
Remove Item Triggered on Load of Page

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#211]
**Describe the bug**
The remove item function is triggered every time the upload [component renders](https://upmostly.com/tutorials/react-onclick-event-handling-with-examples). It currently reads:
[`<IconButton icon={true} onClick={removeItem(i)}>`](https://github.com/openoakland/woeip/blob/081ca917b25e1244eb86ceb901134b70d1f9ed7a/web/src/components/Upload/index.tsx#L176)
It should read:  ~~`<IconButton icon={true} onClick={() => removeItem(i)}>`~~  to make it only activate when the trash button is clicked. Change to [follow pattern](https://github.com/wmonk/create-react-app-typescript/issues/370#issuecomment-426643150) that doesn't utilize lambda function in JSX attribute, in line with [performance recommendations](https://github.com/wmonk/create-react-app-typescript/issues/370#issuecomment-409181765). It now reads `<IconButton icon={true} data-arg={i} onClick={removeItem}>` with the `removeItem` function changed accordingly.

The function itself also uses a filter and returns a callback. It would be more efficient to use a splice (as we're already using an index) and to trigger a refresh simply by updating the state.
[Change:](https://github.com/openoakland/woeip/blob/081ca917b25e1244eb86ceb901134b70d1f9ed7a/web/src/components/Upload/index.tsx#L144)  
```
  const removeItem = (removableIndex: number) => {
    return () => setFiles(files.filter((_, i) => i !== removableIndex))
  }
```
to read:
```
  const removeItem = (removableIndex: number) => {
    files.splice(removableIndex, 1)
    setFiles([...files])
  }
```

**To Reproduce**
Add a console.log to removeItem function, load the upload page, and view the console in developer tools.

**Expected behavior**
removeItem should only trigger when the trash item is clicked.

**Rider Update**
Warning that `innerRef` is deprecated (within dropzone props). Replace with `ref`

**Comment by joshling1919** [comment]
good catch/optimization! we should probably avoid calling splice on `files` since that mutates the state, but removing the returned callback sounds good to me.

**Comment by TangoYankee** [comment]
There is also a warning from `innerRef` being deprecated. I'd like to include that in this fix.
