### ISSUE TITLE
Check type of file

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#216]
**Is your feature request related to a problem? Please describe.**
Checks for the type of file rely on the type of file being in the name. ie a `dustrak` file will have `dustrack` in the name. This check is prone to the file being renamed. I would like a more robust pair of checks.

**Describe the solution you'd like**
The type of file is listed as part of the metadata. Additionally, the content of the file indicates what kind of file it is. ie) A dustrak file will say in the text of the file content that it is a Dustrak File. I would like a pair of check that first check the file type. Then when it extracts the content, it checks the content is valid. Failing either of these checks will stop the upload process and return an error.

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
- [Backend serializer](https://github.com/openoakland/woeip/blob/master/api/woeip/apps/air_quality/serializers.py)
- [Frontend validator](https://github.com/openoakland/woeip/blob/master/web/src/components/Upload/util.ts)

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
Wireframes or other design resources

**Testing Outline**
Describe the testing methods appropriate for this feature

**Comment by theecrit** [comment]
@TangoYankee Does this still need definition or can we move it into `Ready`?

**Comment by TangoYankee** [comment]
I'm good with calling it ready is @nbilenko is
