### ISSUE TITLE
Passing uploaded files and data between upload and confirmation pages on the frontend before API call. 

### ISSUE THREAD

**Issue by Ajay-Vishwanath** [openoakland/woeip#219]
**Is your feature request related to a problem? Please describe.**
Part of Issue #132.
The upload page will pass the uploaded files and parsed data to the confirmation page which will eventually make the post request with the updated data to the endpoint. 

**Describe the solution you'd like**
I would like the FormData object to be passed from the upload page to the confirm-upload page when the user clicks upload on the upload page, and for that updated FormData object to be sent to the backend upon confirmation. I believe this can just be done in React-Router, and am trying to figure out that implementation. 

**Describe alternatives you've considered**
We could use Redux for state management, but that seems heavy and unnecessary. Open to any alternatives folks may have so please chime in. 

**Additional context**
If we don't have a device-parsing utility function, users would select their device on the confirmation page and that would just be appended onto the existing form data before upload. 

**Labels**

- [x] Add a status label
    - Discussing

- [ ] Add additional labels as needed

### For Developers
**Affected Components**
Upload and Confirm-Upload components.

**Design Documentation**

- [Database Schema](https://user-images.githubusercontent.com/32755410/80737017-cb2bed00-8ac7-11ea-9282-5836501a5fb6.png)
- [Wireframes](https://www.figma.com/file/IZw8VvX1CsRc764CTvg4aRSU/WOAQ-Wireframes-Parent-File?node-id=753%3A6848)

**Comment by TangoYankee** [comment]
Could we combine the `Upload` and `Confirmation` pages onto one route/url path? We would render one or the other sets of components based on some state that's derived from the validation step. Ie) The `upload button` is shown only when there is no error message. We would change it so that the `Confirmation components` are shown when there is no error message. 

It would look like two separate pages-as in the wire frames. However, both sets of components would live on the `/Upload` route. This should be possible without Redux. What do you think @joshling1919 ?

**Comment by joshling1919** [comment]
@TangoYankee That idea sounds good to me!

If you ever did end up wanting to separate them into two routes, something like `useContext` (https://medium.com/@seantheurgel/react-hooks-as-state-management-usecontext-useeffect-usereducer-a75472a862fe) might be a good choice as a lightweight alternative to redux.

**Comment by theecrit** [comment]
Are there dependencies between this issue and #209, which outlines the unvalidated data flagging process?

**Comment by TangoYankee** [comment]
> 
> 
> Are there dependencies between this issue and #209, which outlines the unvalidated data flagging process?

There are two stages of checking the files. The first is a front end check that the correct files were dropped onto the page and their times match. The second is a backend check where someone manually reviews the data and flips a `flag` in the database. Issue #209 touches on both these aspects of file checking/validating. This issue (#219) depends on the front end checks but is independent of the backend `unvalidated data flagging`.

**Comment by Ajay-Vishwanath** [comment]
> @TangoYankee That idea sounds good to me!
> 
> If you ever did end up wanting to separate them into two routes, something like `useContext` (https://medium.com/@seantheurgel/react-hooks-as-state-management-usecontext-useeffect-usereducer-a75472a862fe) might be a good choice as a lightweight alternative to redux.

Thanks for this resource @joshling1919! @TangoYankee - this seems like a more lightweight way of passing state between the two components and could allow us to have separate routes for upload and confirmation (i.e /upload and /confirm-upload pages). Do we want to keep these two pages separate or under one url? @theecrit any thoughts here?

**Comment by TangoYankee** [comment]
@Ajay-Vishwanath Whatever you feel most comfortable with implementing

**Comment by theecrit** [comment]
> Do we want to keep these two pages separate or under one url?

Are there compelling pros/cons for either? Any use case for eventually needing to link to the confirmation page specifically? (I don't think that's likely.)

Having the two URLs could help reinforce/communicate progress to the user, so perhaps that's enough reason to differentiate.

**Comment by theecrit** [comment]
Will continue with single-route for MVP.
