### ISSUE TITLE
Reset files state only on success: Front End Upload

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#222]
this is unrelated to your PR, but it just occurred to me that we should probably move `setFiles([])` that's currently on line 154 to inside the success `then` block so that we don't clear their files until it has successfully hit the API. I'm sure lots will change soon with the upload logic, but just wanted to note that.

_Originally posted by @joshling1919 in https://github.com/openoakland/woeip/pull/214_

**Comment by theecrit** [comment]
@TangoYankee Could you rewrite this issue so it's able to be picked up by someone with relatively little project context? Maybe something like current situation > what needs to change/why > any necessary documentation and/or relevant dependencies?

**Comment by theecrit** [comment]
Also, should this be considered MVP?
