### ISSUE TITLE
As User, I want the Device Name to be detected automatically from the file

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#232]
**Is your feature request related to a problem? Please describe.**
The dropdown field in the upload confirmation component is a list of devices that don't necessarily reflect the actual device names used by EIP.

**Describe the solution you'd like**
I would like the device name field to be populated by the name listed in the dustrak file

**Describe alternatives you've considered**
Currently, it is a predefined list of device names.

**Additional context**
We need to resolve the idea of a field pre-filled by the listed name with the idea of using a dropdown list of options. Perhaps we can pull a list of options from the database?

**Labels**
- [ ] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [ ] Add additional labels as needed

### For Developers
**Affected Components**
List what pages or backend files will need to be added, removed, or changed

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
Wireframes or other design resources

**Testing Outline**
Describe the testing methods appropriate for this feature

**Comment by TangoYankee** [comment]
Related Issue #132

**Comment by theecrit** [comment]
@TangoYankee @Ajay-Vishwanath I'll let you two update this to reflect the decision we just made for MVP (pulling device nickname from within front-end).

**Comment by TangoYankee** [comment]
Serial Numbers: 
- 8530091203 -> A
- 8530094612 -> B
- 8530100707 -> C

**Comment by TangoYankee** [comment]
@theecrit We're also getting rid of the option to change the device via a dropdown, right? We're treating it as another thing the computer knows more reliably than the user?

**Comment by theecrit** [comment]
> @theecrit We're also getting rid of the option to change the device via a dropdown, right? We're treating it as another thing the computer knows more reliably than the user?

Yep!
