### ISSUE TITLE
Error when upload non-csv and gps.log files

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#235]
**Describe the bug**
"When you upload non-csv and gps.log files, the page errors out and says 'Unhandled Rejection(TypeError): Cannot read property 'text' of undeined'. That error stems from the upload confirmation component which shouldn't be hit unless file length and error message checks are met which is interesting"
- @Ajay-Vishwanath 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Labels**
- [ ] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [ ] Add a `bug` label
- [ ] Add additional labels as needed

**Affected Components (For Developers)**
List what pages or backend files will need to be added, removed, or changed

**Technical Resources (For Developers)**
Add links to appropriate documentation. Describe possible code implementations.

**Comment by Ajay-Vishwanath** [comment]
**Error Reproduction**

1. Go to the upload page.
2. Drag/Drop or select 2 non-csv or log files - I chose .png files for instance.
3. Browser responds with this error:
<img width="1137" alt="Screen Shot 2020-06-24 at 3 53 09 PM" src="https://user-images.githubusercontent.com/47573228/85635583-0adc0480-b633-11ea-8651-13ba9c2b0174.png">

The source of this error is in the upload-confirmation component. Somehow that component is being rendered without the checks having been met - I will look into this and let you know if I don't make progress.

**Comment by Ajay-Vishwanath** [comment]
**Proposed Solution**

In the current implementation, the checks are being met (`file.length` = 2 and no `errorMessage`) before `handleValidation` is called, and the confirmation component is then rendered with the incorrect files. We need to make sure `handleValidation` is called on the uploaded files and returns no `errorMessage` before proceeding. 

One solution would be to have another variable in state called `proceed`. The default value of that can be set to false - and in the `handleValidate` function, if the validateFiles utility function returns no error on the uploaded files, we can set `proceed` to true. The confirmation component is then only rendered if `file.length === 2 `and `proceed === true`. 

Seems to work on my end, let me know what you think.
