### ISSUE TITLE
Display and color code readings on the map

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#237]
## Description
The viewer wants to look at the data points displayed on a map and understand at a glance what the general degree of pollution is for those locations. 

- [ ] Per conversations with WOEIP, we'll color code the data points on the map to reflect their PM2.5 levels, using the 24 hr average EPA color standard for PM2.5 for our air quality readings on the map (see [comment](https://github.com/openoakland/woeip/issues/237#issuecomment-823015400)).
- [ ]  If there are multiple sensor readings for a particular geopoint (same (lon,lat)), I would like the reading for that (lon, lat) point to be the **max** of all the readings. (#318)

### Technical implications and resources

- Starting place to look for potential styling controls in the codebase: web/src/components/map/box.css
- Reference for [Mapbox styles](https://docs.mapbox.com/studio-manual/reference/styles/)
- Related issues: #317, #316

-----

### Archived issue description for posterity
**Is your feature request related to a problem? Please describe.**
AQ Data **for PM2.5 particulate matter** are collected as an absolute measurement of ~~Parts Per Million~~ **milligrams per cubic meter or micrograms per cubic meter**. There should be a classification system in order to provide context to how dangerous the air was during a session

**Describe the solution you'd like**
There should be an algorithm / set of rules to classify the AQ. The rules should be open source, to give users a way of challenging the assumption we made in developing the rules. The rules should reflect best practices for Public Health.

**Describe alternatives you've considered**
Instead of a classification system, we could present raw statistics, such as min, max, mean, median, and st dev of readings.

**Additional context**
This classification system should provide users a quick way to accurately gauge the danger posed by air pollution.

*Existing classification systems*
- [WHO Air quality guidelines](https://www.who.int/en/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health)
- [EPA National Ambient Air Quality Standards](https://www.epa.gov/criteria-air-pollutants/naaqs-table)

-----

@gsehrlich edited information about units in which data are collected on 5/3/2022. See issue #464.

**Comment by theecrit** [comment]
I'm not sure an entirely new classification system is necessary but I like the idea of challenging the limitations of existing classifications. When we're ready to dig into this, we should also be sure to center the conversation around the work WOEIP has already done here—they already have a set of actual environmental indicators ([pdf attached](https://github.com/openoakland/woeip/files/5012723/neighborhood_knowledge_for_change3.pdf), pp13-19). 

We'll want to explore what a classification system implies:
- Equity comparisons (WO compared to all of Oakland/AC/CA/et al)
- Impacts (on health, transport, etc)
- Impacts on WOCAP work (since they will be measuring actual changes in WO AQ to evaluate whether the strategies are working or not)

etc.

**Comment by kwonangela7** [comment]
Per our conversation with him, Brian's recommendation is to use the 24 hr average EPA color standard for PM2.5 for our air quality readings on the map ([source](https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf)) 
![image](https://user-images.githubusercontent.com/13878545/115349071-40288480-a168-11eb-9f17-f465266d0f8d.png)

I think everything Jess mentioned above are still good things we should consider at some point. However, for the MVP let's stick with Brian's recommendation and use a standard for a 24 hour average even though woaq's air quality numbers for a single session (and even the comparison of sessions) are computed with real time data.

**Comment by kwonangela7** [comment]
@brooksjessup is working on the color coding with @kbrdsk, so I assigned both of them to this one. Since this is a larger ticket, we may end up having several assignees.

**Comment by TangoYankee** [comment]
I see the third acceptance criteria: "see the min or max of air quality per 3 meters" used to be its own issue- #315 . I think it should be split back into its own issue for three reasons.

1) The first two acceptance criteria are already complex
2) The third criteria appears to be an independent feature
3) I think we will want designs that clarify what it looks like to display the min and max, without cluttering or slowing down the map. Do we have those or can we link to them?

**Comment by TangoYankee** [comment]
> Per our conversation with him, Brian's recommendation is to use the 24 hr average EPA color standard for PM2.5 for our air quality readings on the map (source)

The classification for PM2.5 is available in this chart:
![Measurement to AQI](https://user-images.githubusercontent.com/11068062/139540817-aa32d8cf-b762-460c-beaf-c45ebaccf1e9.PNG)

The dustrak measures in mg. The conversion of m to μ is 10^3 μ to m.

**Comment by TangoYankee** [comment]
Still need to write the tests. But, this is the progress I was able to make today. 
![color categories](https://user-images.githubusercontent.com/11068062/139543271-f0963174-f0be-4c8b-868e-d1f0b2bbae64.PNG)

The yellow is hard to see. But, it's correct.

**Comment by theecrit** [comment]
> I see the third acceptance criteria: "see the min or max of air quality per 3 meters" used to be its own issue- #315 . I think it should be split back into its own issue for three reasons.


I'm actually not super clear what the difference is between criteria 2 & 3, other than one addressing when there's more than reading for a single geolocation. 

@kwonangela7 Can you shed any light here?

**Comment by TangoYankee** [comment]
I made two updates.
1) We were using a [`Marker`](https://visgl.github.io/react-map-gl/docs/api-reference/marker) for each data point. This was making our map slow to zoom and pan. As referenced in the description, I swapped it with a style [layer](https://visgl.github.io/react-map-gl/docs/api-reference/layer) for all data points. It's much smoother now.
2) The EPA document lists specific rgb levels for each color. I updated the data circles to use the hex equivalent.

![EPA colors](https://user-images.githubusercontent.com/11068062/139733695-759b13c7-c14a-441b-8ddf-833160470b32.PNG)

**Comment by kwonangela7** [comment]
> I'm actually not super clear what the difference is between criteria 2 & 3, other than one addressing when there's more than reading for a single geolocation.

@theecrit that's exactly the distinction! These stylings are from the meeting we had with Brian a while back (captured from my handwritten notes) and I wanted to lay them down explicitly on this ticket. We're using max as the aggregator for both situations; #2 is for aggregating multiple readings for a single geolocation and #3 is for aggregating multiple readings over a certain area (Brian suggested 3m, I guess we can see what's technically feasible if 3m is a problem).

@TangoYankee That is a really good suggestion (to separate the third from the second issue); I just realized that makes a lot more sense. I actually have a ticket to work on fleshing out the details on this ticket, and I'll split the ticket tomorrow during work session. 

Anyway, thanks for working on the color coding item! As for the third item, per our team discussions a while ago I think we can implement @theecrit 's designs. Tagging Jess as I found the related [Figma file](https://www.figma.com/proto/IZw8VvX1CsRc764CTvg4aRSU/WOAQ-Wireframes-Parent-File?node-id=753%3A813&scaling=contain&page-id=753%3A0), but it doesn't have the exact design that showcases the min/max number as I remember. Jess, am I misremembering?

(Also, thanks for working on this ticket Tim! And sorry, I didn't realize that this ticket wasn't in the "Ready to work on" column yet but it is, even though the third point should have a design like you mentioned)

**Comment by kwonangela7** [comment]
@theecrit tagging you for the comment above as I'm not sure if Github sent the notification due to some formatting issue I had when I first posted the comment.

**Comment by kwonangela7** [comment]
Shoot @TangoYankee -- sorry, I should have made this more obvious on the ticket itself as opposed to just it being a comment but Brooks and Kabirdas actually implemented #2 in Mapbox itself! Kabirdas opened up PR #364 so that we could do stylings in Mapbox (and also use the one Brooks already created for #2, check it out [here](https://api.mapbox.com/styles/v1/bjessup/ckooyp5jf1e0717p6ojtjol3d.html?fresh=true&title=copy&access_token=pk.eyJ1IjoiYmplc3N1cCIsImEiOiJja29hdThpMW0wNTB0Mm5va3hiMTg3MDg4In0.cOpsPQrnbE5-k05WMtLvog#9/37.78/-122.4241)) that would show up on the website.

However, being that I'm not a web developer myself, I'm not sure if it's better to have it done on Mapbox and use Kabirdas' code to have it show up on the app, or to do it through React (as I'm guessing you did?). Anyway, sorry for this situation where we have two solutions for the same problem!

**Comment by TangoYankee** [comment]
Having the feature depend on an outside style is fragile. If the map breaks or we need to change it, it is difficult or impossible for another developer to manage it.

The application is designed to use react and mapbox directly in the front end. This allows any developer to have direct access to how the data is displayed. It also gives us more control to optimize its performance and add new features, such as #331 .

**Comment by kwonangela7** [comment]
I went ahead and moved the third item into #315; thanks for your patience!

@TangoYankee, I will follow up with Jess directly about the designs for the max/min. I'm not sure if we have any atm but I imagine we can come up with something relatively quickly. Is there any other information needed from me (other than the designs) to ensure this ticket is ready to be worked on?

Happy to jump on a call sometime to discuss, if it's easier to go back and forth there. Thanks!

**Comment by kwonangela7** [comment]
I went ahead and moved the third item into #315; thanks for your patience!

~~@TangoYankee I put this ticket back in needs definition b/c item #2 needs more. What I currently have for designs for item #2 are the [wireframes](https://www.figma.com/file/IZw8VvX1CsRc764CTvg4aRSU/WOAQ-Wireframes-Parent-File?node-id=340%3A5671) for the Figma prototype linked in a previous comment. However, the design shows more requirements than what's on this ticket, so it needs to be further broken down to be useful for this ticket.~~

~~I'm going to try to set up a time with Jess to further clarify, and hope to have an update soon.~~ 

Sorry @TangoYankee, I misspoke back when I wrote this comment. #2 does have a design (as you've already implemented). The dot representing the reading along the path should take on the color of the max reading.

~~In the meantime, let me know if there's any other information that I need to provide to make this ticket ready to work on for a dev. Thanks!~~ Not needed; Tim already finished this ticket!

**Comment by theecrit** [comment]
@kwonangela7 

> However, the design shows more requirements than what's on this ticket, so it needs to be further broken down to be useful for this ticket.

Are you referring to the pop-up for an individual geolocation? That is covered by #331 and is not within the scope of this issue, so shouldn't be a blocker. This issue is for the route path display only.

**Comment by kwonangela7** [comment]
@theecrit -- you're totally right, and I finally got around to updating the comment above. Sorry for the confusion!

**Comment by kwonangela7** [comment]
@mnorelli, Tim actually has a PR open for this work! https://github.com/openoakland/woeip/pull/380

I'm going to take you off as an assignee for this ticket since Tim completed it, but I added you as a reviewer to the PR as I thought you'd be a great person to do it! Hopefully this is okay with you, but take yourself as an assignee if not.

(Apologies that I didn't realize this work was already done 😅 )
