### ISSUE TITLE
[Enhancement] Update ReadMe and Contributing files to make onboarding smoother

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#252]
### Description
While previous improvements made it easier for new team members to get up and running, the current ReadMe and Contributing docs are still a little long-winded and not super easy to navigate. The Contributing.md file is outdated at this point and may over-document the process to the point of being overwhelming/confusing. 

### Recommended updates
- [ ] Consider adding the basic steps for installing Docker Compose and/or link to https://docs.docker.com/compose/install/
- [ ] Make "Browse the client at lvh.me, ping the api at api.lvh.me." more explicit. I.e. "View the front-end in your browser at lvh.me" etc.
- [ ] Explain "Services" section more explicitly in plain language
- [ ] Add a reference to the API's swagger docs (?)
  - `api.lvh.me/swagger` - TY 
- [ ] Condense the workflow description and include it in the ReadMe, eliminating the need for a separate doc.
- [ ] Correct header hierarchy for easier scanning/visual simplicity
- [ ] Update technologies list - TY
  - Zurb -> Semantic UI
  - TSLint -> ESLint (Pending PR #251 / Issue #250 )
  - Black -> Doesn't seem to actually exist in the code? Also, I prefer autopep8. Black can sometimes lead to obnoxious line formatting.

### Good examples worth borrowing from
- https://github.com/openoakland/openbudgetoakland

PR #253 -TY

**Comment by TangoYankee** [comment]
> Condense the workflow description and include it in the ReadMe, eliminating the need for a separate doc.

If we want to get rid of the contributing doc, we can also utilize the [Pull Request Checklist](https://github.com/openoakland/woeip/blob/master/.github/pull_request_template.md) to guide the contributing process i.e) *Make sure you run your tests and linters*

**Comment by theecrit** [comment]
> If we want to get rid of the contributing doc, we can also utilize the [Pull Request Checklist](https://github.com/openoakland/woeip/blob/master/.github/pull_request_template.md) to guide the contributing process i.e) _Make sure you run your tests and linters_

I didn't even realize that existed.
