### ISSUE TITLE
Improve UX on map loading

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#257]
## Description
Currently, when a user clicks "Save" there is a lag between the click and the time the system pushes them to the map page. Presumably, this is because the system is writing the data from the files to the database during this time, so it can render the map on the next page using those data points. However, there's no visual feedback for the user, so it seems like something is broken.

## Proposed solution
We'd like better visual feedback for the user that communicates:

- The system has received your save request
- The system is processing your request and doing something relevant
- This process is worth waiting for

After some team discussion around progress indicator styling, I'm suggesting the following (this is open to discussion):

- [ ] Add universal button styling* for hover and on:click behavior to improve user feedback.
- [ ] On clicking "save," the user is pushed to the map page immediately.
- [x] ~Placeholder content is displayed in the locations that are still waiting for the data to write to the database (including sidebar metadata).~
- [x] ~In the map area, add a [Semantic UI loader icon](https://react.semantic-ui.com/elements/loader/).~ 
 - ~Suggestions: I prefer the slower speed of the ["States" version](https://react.semantic-ui.com/elements/loader/) over the others, and suggest using a size somewhere in the middle; suggest using a dimmer for the entire map area to reinforce that that is the primary content area.~
- [x] ~The loader should be accompanied by text reading something to the effect of "Loading your map..." (ellipses indicate something is happening next).~
- [ ] Bonus points: let's brainstorm a list of short prompts or facts that we can display randomly every 5 seconds (assuming it takes at least 5 seconds generally to load the map).

_* This should be a global css style for all primary and secondary buttons._

**Describe alternatives you've considered**
- Using a progress indicator instead of loader is not quite as specific/accurate.
- Keeping the user from advancing to the view map screen until data is fully saved makes the process feel unnecessarily long; moving them to the map page at least let's them experience some progress/reward. 

**Additional context**
If devs would like wireframes, we can make that happen. Let me or Niels know in Slack.

### For Developers
**Affected Components**
List what pages or backend files will need to be added, removed, or changed

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
Wireframes or other design resources

**Testing Outline**
Describe the testing methods appropriate for this feature

**Comment by theecrit** [comment]
@Ajay-Vishwanath I'm going to close this and open a separate issue for the lag on "save," which still seems to be occurring.

**Comment by Ajay-Vishwanath** [comment]
@theecrit Sounds good - had a small note about that in my pr:

> Part of issue #257 - specifically about the second checkbox - pushing the user to the map immediately after clicking save. I don't think this will be ideal with what's happening under the hood - the collections for the specific dates are called as soon as the component is mounted, and if we push to the map page without the newest collection being successfully saved yet, I can see it not coming up. I think there should be some loading indicator on the upload page after clicking save that we could design out.

**Comment by theecrit** [comment]
@Ajay-Vishwanath Oh yeah, that makes loads of sense (no pun intended). I'll update #280 accordingly.
