### ISSUE TITLE
Initial Error from Collection Date API Request

### ISSUE THREAD

**Issue by Ajay-Vishwanath** [openoakland/woeip#258]
**Describe the bug**
When changing the date on the Map Display page, the initial `collectionDateRequest` API call errors out which is printed to the console. This is not a huge deal as the next request is a successful 200-level request, but is worth fixing.

**To Reproduce**
1. Go to the Maps page
2. Open the Chrome console
3. Change the date 
4. See that cancel was logged in the console and a faulty network request was made

**Expected behavior**
A successful initial request.

**Screenshots**
Ajay can send you a screenshot if needed.

**Labels**
- [X] Add a status label
  - `needs definition`
  - `needs help`
  - `ready to work on`
  - `in progress`
  - `backlog`
- [X] Add a `bug` label
- [X] Add additional labels as needed

**Affected Components (For Developers)**
Map Index Component

**Comment by kbrdsk** [comment]
This seems to have been fixed in PR#288, cancel is still logged to the console but no more faulty requests are being made.

**Comment by theecrit** [comment]
Closing per @kbrdsk's observation above.
