### ISSUE TITLE
Device Name Saved to the Database

### ISSUE THREAD

**Issue by Ajay-Vishwanath** [openoakland/woeip#259]
## Description
WOEIP uses three DustTrack units, nicknamed `A`, `B`, and `C`. Currently, this comes into play in two places in the user flow:

1. On the Confirmation page (between Upload and View Map)
2. On the View Map page

We need to ensure the system is pulling and displaying the data accurately. Right now:

- [ ] The Confirmation page displays a proper device nickname, but I'm not sure if this is pulling from the actual database or if this is dummy text. We need to confirm if that's the case.
-  [ ] The View Map page is displaying the wrong string. That needs to be corrected.

Previously, we'd discussed that we would pre-populate the database's `Device` table with the three device nicknames (A, B, and C). To do this, we need to figure out which nickname applies to which serial number (the SNs are: 8530091203, 8530094612, and 8530100707). 

For the purpose of this issue, let's assign them arbitrarily and open a bug to correct the `name` fields once we have that info:

**Table: Device, Record 1** 
- Serial: 8530091203
- Name: DustTrak A

**Table: Device, Record 2** 
- Serial: 8530094612
- Name: DustTrak B
- 
**Table: Device, Record 3** 
- Serial: 8530100707
- Name: DustTrak C

### Confirmation page 
Confirm that the system:

- Identifies the `Serial Number` from the uploaded CSV file.
- Queries the `Device` table in the database for the `Serial Number`.
- Calls the associated `Name` field for that record in the "Device" field on the View Map page.

### View Map page
The View Map page displays a field for `Device`, which should display the nickname assigned to the particular DustTrak that collected the data. To get there, the system needs to:

- Query the proper table in the database to call the `name` field from the proper `Device` table record and display it in the "Device" field on the front-end.

## Original issue

**Is your feature request related to a problem? Please describe.**
We need the device type from the upload flow to be saved to the database in order to pull that information up on the session information section of the map display page.

**Describe the solution you'd like**
Append the device type to the `formData` in the upload confirmation page and save that information to the collection.

**Comment by theecrit** [comment]
@Ajay-Vishwanath I think you're using _device type_ but really mean _device name_. 

- Device type = model (e.g. DustTrak), which isn't technically used anywhere in the [database](https://drive.google.com/file/d/1U5tIkROnRMZkQJXmoQan81WKCapi7fOy/view?usp=sharing).
- Device name = nickname for each of the 3 DustTrak devices (which is what we want to display on the front-end, and is reflected in the `name` field in the `Device` table according to our [schema](https://drive.google.com/file/d/1U5tIkROnRMZkQJXmoQan81WKCapi7fOy/view?usp=sharing))

I've updated this issue with more specifics to capture the nuances and tagging @TangoYankee to ensure I've captured everything accurately.

**Comment by Ajay-Vishwanath** [comment]
Noticed that the app still doesn't save the `device_id` to the `collection` object upon creation, and can't display which device made which collection on the view map page. I think some backend work needs to happen first where there is an association made between those two tables and then the device_id is added to the `collection` object within the Collection Serializer. I will handle this and then handle displaying that device name on the view map page after. The work that has been done for the confirmation component will be helpful there.

**Comment by TangoYankee** [comment]
@Ajay-Vishwanath Looking at the [database schema](https://drive.google.com/file/d/1U5tIkROnRMZkQJXmoQan81WKCapi7fOy/view), it seems that the device is linked via the sensor and the sensor is linked via the collection file and the collection file is linked to the collection. Fun. Anyway, a lot of discussion went into [normalizing the database](https://en.wikipedia.org/wiki/Database_normalization). I wouldn't want to modify the structure without a strong need. 

In this instance, I would focus on the Sensor table because it is the missing link in the chain from collection to device. This would entail two main steps. First, seed the Sensor Table the same way we seeded pollutants and devices. Seed the Sensor after the Device, so that it can be seeded with the now-existing Device id.  Then, modify the backend to set the Sensor Id field when saving the Dustrak Collection File. This will complete the link it to Device.

**Comment by theecrit** [comment]
@wendy-wm-wu Do you know which PR this fix ended up in? Would love to document that before officially closing this issue.

**Comment by wendy-wm-wu** [comment]
@theecrit - https://github.com/openoakland/woeip/pull/323
