### ISSUE TITLE
Links to Open Session Files on the Map Page

### ISSUE THREAD

**Issue by Ajay-Vishwanath** [openoakland/woeip#260]
**Is your feature request related to a problem? Please describe.**
On the Map display mockup on figma, there is a link to 'view raw data' in the bottom of the session information. We need this to open the CSV and GPS log files that were uploaded for that session.

**Describe the solution you'd like**
Implementation of a 'view raw data' link that either downloads those 2 files or opens them up in separate tabs.

**Additional context**
The files are already held in the `currentCollection` object that exists in the ControlPanel state. Just a matter of creating a link that opens up those files. 

**Labels**
- [x] Add a status label
  - `needs definition`
  - `needs help`
  - `ready to work on`
  - `in progress`
  - `backlog`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
ControlPanel component.

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
Figma design found [here](https://www.figma.com/file/IZw8VvX1CsRc764CTvg4aRSU/WOAQ-Wireframes-Parent-File?node-id=753%3A813)

**Testing Outline**
Describe the testing methods appropriate for this feature

**Comment by theecrit** [comment]
Quick question re: the UX flow here. "View raw data" implies the interface will display the data, whereas "Download raw data files" is more accurate for the behavior described in the issue. I don't have a strong opinion either way, other than to make sure the language matches the behavior. 

Viewing raw data in the interface probably requires more development overhead (New window/view or modal overlay? What kind of formatting and styling? Add a download link, too?). So maybe we default to "Download raw data files" and if users seem to want to view the data first, we can build that out later?

**Comment by Ajay-Vishwanath** [comment]
> Quick question re: the UX flow here. "View raw data" implies the interface will display the data, whereas "Download raw data files" is more accurate for the behavior described in the issue. I don't have a strong opinion either way, other than to make sure the language matches the behavior.
> 
> Viewing raw data in the interface probably requires more development overhead (New window/view or modal overlay? What kind of formatting and styling? Add a download link, too?). So maybe we default to "Download raw data files" and if users seem to want to view the data first, we can build that out later?

@theecrit Definitely agree - we should make it say 'download raw data' and have it just do that for now.

**Comment by theecrit** [comment]
Works for me!

**Comment by Ajay-Vishwanath** [comment]
@theecrit did we get this fully working with download raw data taking us all the way there? Was 90% of the way there with my last PR
