### ISSUE TITLE
Loading Indicator on Map While Markers are Being Placed

### ISSUE THREAD

**Issue by Ajay-Vishwanath** [openoakland/woeip#262]
**Is your feature request related to a problem? Please describe.**
In addition to the loading feature on file upload outlined in #257, we need a loading indicator once the markers are being generated before they are placed on the Mapbox map. 

**Describe the solution you'd like**
Have a loading indicator above the Mapbox map which disappears once the markers have been generated and placed.

**Additional context**
We might want to wait until new data viz ideas are brought to life, but I imagine the logic will still be the same. 

**Labels**
- [x] Add a status label
  - `needs definition`
  - `needs help`
  - `ready to work on`
  - `in progress`
  - `backlog`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
Map Index.

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
Wireframes or other design resources

**Testing Outline**
Describe the testing methods appropriate for this feature

**Comment by theecrit** [comment]
@Ajay-Vishwanath If I understand what you're saying, #257 would add a loader to load the map layer, and then this issue would add another separate loader while loading the data layer? I'm wondering if it would be more seamless for the user if we just left the #257 loader going until both map and data were loaded. Thoughts?

**Comment by Ajay-Vishwanath** [comment]
> @Ajay-Vishwanath If I understand what you're saying, #257 would add a loader to load the map layer, and then this issue would add another separate loader while loading the data layer? I'm wondering if it would be more seamless for the user if we just left the #257 loader going until both map and data were loaded. Thoughts?

@theecrit I think we can delete this issue and consolidate with #257, I didn't read the solution closely enough. We also need to have that same loading indication happen when users change dates or sessions and not just when they are pushed over from upload, but that should be the same implementation.
