### ISSUE TITLE
Document how to access the actual database in the ReadMe

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#265]
## Desription
The current ReadMe doesn't walk new contributors through the process of spinning up and accessing the database.

## Proposed solution
Add step-by-step instructions to the ReadMe so anyone can access and start querying the database directly via SQL e.g.

**Describe alternatives you've considered**
Simply viewing the schema and pinging the API limits how different thinkers might approach working with the data, which limits what we can do/design/build.

## Related documentation
- [Schema](https://drive.google.com/file/d/1U5tIkROnRMZkQJXmoQan81WKCapi7fOy/view?usp=sharing)
- [ReadMe](https://github.com/openoakland/woeip/blob/master/README.md)

**Comment by TangoYankee** [comment]
1) This would only be available for local machines as the Api exists specifically to control how people interact with the db.
2) With the KISS rewrite of the readme, we took out everything that isn't 'run this with docker'
3) Once the docker containers are running as outlined in the readme, the db can be accessed directly with the following commands:
1. `docker-compose exec db bash` (enters the docker container, which is basically a mini-linux machine)
2. `psql -U postgres` (logs in to the database that is running on the mini-linux machine)
3. `\c woaq` (enters the woaq database)
4. SQL until one's heart is content

**Comment by theecrit** [comment]
Duplicate of #276
