### ISSUE TITLE
Update ReadMe for accuracy

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#276]
Current ReadMe is out of date. 

- [x] Replace "West Oakland Air Quality (WOAQ) is a project of OpenOakland focused on building digital advocacy tools around air quality data collected by volunteers and citizen scientists." with `West Oakland Air Quality (WOAQ) aims to help West Oaklanders fight for better air by making their local air quality data more accessible and meaningful, and providing the digital advocacy tools needed to drive change in their neighborhood.`
- [x] Add instructions documented in [this comment](https://github.com/openoakland/woeip/issues/362#issuecomment-941882933) for running front-end locally.
- [x] Add instructions documented in [this comment](https://github.com/openoakland/woeip/issues/265#issuecomment-728645463) for accessing the database within a local Docker container, as well as a reference to the [db schema docs](https://drive.google.com/file/d/1U5tIkROnRMZkQJXmoQan81WKCapi7fOy/view?usp=sharing). 

Dependency for #246

**Comment by hawser** [comment]
Much better. Feels long in a single sentence to my ear. Another option,

West Oakland Air Quality (WOAQ) was founded in support of the West Oakland community. We strive to make local air quality data more accessible and meaningful. With the necessary digital advocacy tools, we drive change in the neighborhood.

**Comment by theecrit** [comment]
Recommended update:

> West Oakland Air Quality (WOAQ) is a platform for impacted communities to understand their local air quality and advocate for environmental justice. With a focus on West Oakland, Calif., a community disproportionately impacted by toxic air pollutants, WOAQ allows citizen scientists living in the neighborhood to upload, view, and explore hyper-local air quality data, and apply their learnings to local advocacy efforts.

**Comment by theecrit** [comment]
Updated instructions for bullet #2 in issue above (for running front-end locally):


Clone repo to your local machine and navigate to the front-end directory:
- `cd ~/{local path}/woeip/web`

Create and check out new branch based on an existing branch:
- `git status` (tells you which branch you're on)
- `git checkout {existing-branch}` (checks out the branch you want to work from)
- `git pull origin {existing-branch}` (pulls latest changes from branch)
- `git checkout -b {new-branch-name}` (creates and checks out a new branch based on the existing one)

Open web browser and text editor. In text editor, `package.json` file contains npm commands under "scripts."

In terminal/command line, run the front-end:
- `npm install` (installs all needed libraries)
- `npm start` (should open in web browser)

In text editor:
- Make desired changes to files in `/src` folder

Stage, commit and push changes:
- `git add .`  (don't forget that period!)
- `git commit -m "{message text}"`
- `git push origin {new-branch-name}`

Open PR in WOEIP repo:
- Request review from team member(s)
