### ISSUE TITLE
Add Latitude/Longitude to Sensor.unit_choices

### ISSUE THREAD

**Issue by r-b-g-b** [openoakland/woeip#28]
Sensors that record GPS location should be marked as having a unit of Latitude/Longitude.

**Comment by Ethan-bradley** [comment]
Is anyone currently working on this?

**Comment by TangoYankee** [comment]
@Ethan-bradley you are?

**Comment by Ethan-bradley** [comment]
Yes

**Comment by Ethan-bradley** [comment]
Does this mean having the latitude/longitude in the unit_choices dropdown or having a separate dropdown with lat/lon as an option?

**Comment by TangoYankee** [comment]
Having lat/long as part of the unit_choices dropdown. It should be written as one entity ie) 'latlong'

**Comment by Ethan-bradley** [comment]
thanks for clarifying.
