### ISSUE TITLE
Testing Switch

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#295]
Tests for switch result in this error: 
```
    Cannot find module 'worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker' from 'src/components/map/box.js'
```

## Acceptance Criteria
- [x] Resolve Error
- [x] Do not break production build of map that is using hack that is triggering error
- [x] Write unit tests for switch component

**Comment by theecrit** [comment]
@TangoYankee Is this a critical bug required for go-live functionality? Can it be moved into either "Ready to work on" or the P2 post-MVP project backlog?

**Comment by TangoYankee** [comment]
Yes, it can be moved to post MVP. It affects our ability to run unit tests. But, we're not really enforcing unit tests.
