### ISSUE TITLE
Production and Development Styling do not match

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#296]
# Description
Some Semantic UI React components look tiny when compared to their development version

## Acceptance Criteria
- [ ] Production styling matches development styling

**Comment by theecrit** [comment]
@TangoYankee Is this a post-MVP improvement, do you think?

**Comment by TangoYankee** [comment]
> @TangoYankee Is this a post-MVP improvement, do you think?

yes. It will likely be resolved when we start applying our custom designs

**Comment by theecrit** [comment]
I'm not seeing this fixed in #379 but let me know if I'm missing something.

**Comment by TangoYankee** [comment]
> I'm not seeing this fixed in #379 but let me know if I'm missing something.

It is certainly possible I missed something. However, not all of the environments would immediately see a difference. Which environments haven't updated?
