### ISSUE TITLE
As a user looking at a single collection session, I would like to see an aggregated min or max value along the path

### ISSUE THREAD

**Issue by kwonangela7** [openoakland/woeip#315]
## Description
The viewer wants to look at the data points displayed on a map and understand at a glance what the general degree of pollution is for those locations, without being overwhelmed by each reading for every single unique point along the path.

### Technical Details
The proposed implementation plan is to pass a parameter to the database (i.e. n, which represents the size of the sample of particular readings) and then get the max of those readings for each group. Read Tim's comments below for more context.

### Related Issues
#385

**Comment by theecrit** [comment]
@kwonangela7 I think this can also get rolled into #237 (along with #318).

**Comment by kwonangela7** [comment]
@theecrit Is there a particular way I should roll up the issue? I'm thinking I'll just note this requirement on this ticket (and the one from #318) under #237's "Describe the solution you'd like"

**Comment by theecrit** [comment]
@kwonangela7 Yep, I'd just add the requirements to the description, tagging these two issues, then go ahead and close them.

**Comment by kwonangela7** [comment]
Closing as this requirement has been moved to #237

**Comment by kwonangela7** [comment]
Per Tim's suggestion (see [comment](https://github.com/openoakland/woeip/issues/237#issuecomment-955389956)) I am reopening this issue and removing it from #237.

**Comment by kwonangela7** [comment]
@TangoYankee, I will follow up with Jess directly about the designs for the max/min. I'm not sure if we have any atm but I imagine we can come up with something relatively quickly. 

Is there any other information needed from me (other than the designs) to ensure this ticket is ready to be worked on? I'm not sure if the backend is set up so that we can actually aggregate the data points as such, so we might need to consider aggregating points within a wider radius. I'm sure there are other dev considerations that I'm blind to, so lmk if you'd be free to chat about how I can help to define this ticket.

Also, should I split this work into backend and frontend work? 🤔

**Comment by TangoYankee** [comment]
@kwonangela7 How are we defining `per 3m`, as the routes often meander. Are we picking every nth reading and finding the readings that are within a 1.5m radius from the reference reading? Are we establishing a grid of 3m by 3m cells and then aggregating all of the readings within that cell? Are we outlining an "ideal" route, picking points along the "ideal" route and then finding readings with a 1.5 radius of those points?

Also, are we trying to make the areas mutually exclusive? If a route turns a corner or doubles back, two different "3m" ranges may overlap, unless we determine a criteria to exclude them.

**Comment by kwonangela7** [comment]
Those are really good questions.. 🤔 (and sorry for the late response!) 

I'm going to think on it a bit more, and see if I can pick the team's brain (namely Jess / Niels since they were at the meeting) on Tuesday and get back to you in a few days. My gut feeling is that we want to establish a grid of 3m by 3m cells and then aggregating all of the readings within that cell, and that we aren't trying to make the areas mutually exclusive... but that seems kind of complicated and still unclear to implement.

**Comment by TangoYankee** [comment]
@kwonangela7 Honestly, I think the simplest approach is to be a little loose with the idea of "3m". Instead, we create groups of size "n" . For example, we could group together every 50 consecutive readings. Those 50 readings will cover some time t. In most circumstances, the collectors will be walking during the collection. The groupings should naturally follow a relatively consistent geographic distribution.

If we perform these groupings on the back end, we might also be able to decrease the time to initially load the map. Fewer raw readings would need to be sent over the network.

**Comment by kwonangela7** [comment]
@TangoYankee I can't picture yet how that would be translated into code 🤔 but I think that makes more intuitive sense. 

Also FYI after the Tuesday worksession this ticket got pushed back as a post-MVP enhancement, but I think this concept relates to other tickets as well. I'll be updating the other ticket you commented on a bit more to fill you in on what we discussed within the next few days.

**Comment by mnorelli** [comment]
Fascinating discussion.  Is this the best place to comment now that this ticket is moved to post-MVP?  Please let me know where else to comment on this display discussion useful to other tickets.

> I'm going to think on it a bit more, and see if I can pick the team's brain (namely Jess / Niels since they were at the meeting) on Tuesday and get back to you in a few days. My gut feeling is that we want to establish a grid of 3m by 3m cells and then aggregating all of the readings within that cell, and that we aren't trying to make the areas mutually exclusive... but that seems kind of complicated and still unclear to implement.

There are established GIS processes to filter data this way, for example the [generalize](https://desktop.arcgis.com/en/arcmap/10.3/tools/editing-toolbox/generalize.htm) geoprocess.  And @TangoYankee I think [simplify.js](https://mourner.github.io/simplify-js/) is the corollary in JS, based on the very clever [Douglas-Peucker algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) which uses a distance tolerance value as the start of an iterative process to discard points within that distance while preserving the curviness of the original line.
For displaying a set of points on the map, this tolerance could be determined dynamically as a function of the zoom level.  Every time you draw the line (at start, or zooming in or out), the points could be filtered on the fly, for example using a larger tolerance when zoomed out (maximum filtering) or a smaller tolerance when zoomed in (less filtered, closer to original data).

**Comment by TangoYankee** [comment]
@mnorelli this is cool

**Comment by TangoYankee** [comment]
> Also FYI after the Tuesday worksession this ticket got pushed back as a post-MVP enhancement

@kwonangela7 @theecrit I would like to advocate for [380](https://github.com/openoakland/woeip/pull/380/files) to go into `develop`. The changes are complete, pending review. They provide functionality that follows the established design and can serve as a foundation for the next set of features.

**Comment by kwonangela7** [comment]
After some back and forth, we're keeping this in the MVP :) I'll be updating the ticket shortly.

**Comment by kwonangela7** [comment]
Ticket has been updated!

**Comment by kwonangela7** [comment]
@TangoYankee @theecrit I created #385 to capture the requirement and implementation details around the zoom levels that we talked about, and linked it to this ticket as well. Please feel free to update either ticket accordingly! ^^

**Comment by theecrit** [comment]
Completed in #331/PR #429
