### ISSUE TITLE
As a user, if there are multiple sensor readings for a particular (lon, lat) point, I would like the reading for that (lon, lat) point to be the max of all the readings.

### ISSUE THREAD

**Issue by kwonangela7** [openoakland/woeip#318]

**Comment by theecrit** [comment]
Related to #315

**Comment by theecrit** [comment]
@kwonangela7 ~Would it be easier to just roll this into #315 as one of the acceptance criteria for that issue to close?~ On second thought let's just roll this and #315 into #237.

**Comment by theecrit** [comment]
Also, for MVP I think the max is fine, but I would love to revisit this post-MVP and see if this is a specific area where we might actually explore creative ways to illustrate the conceptual differences between mean, min/max, range, etc. and what the implications might be for making meaning and applying it to real-world decisions.

**Comment by theecrit** [comment]
Closing, as this has been rolled into #237.
