### ISSUE TITLE
Trello and Github Workflow (Formerly Navigation bar)

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#32]
Implement `Foundation Navigation Bar`

**Comment by theecrit** [comment]
This needs a design card in Trello (I'm starting to see the pattern here re: workflow). My thought is that undefined feature requests should start in the Trello design backlog, then move into a Github Issue once it's defined enough to implement. Is that too much of a bottleneck? I just worry that we're going to end up with duplicate backlogs otherwise.

**Comment by TangoYankee** [comment]
The Trello is becoming a hindrance for code implementation. Trello will be good to document large scope ideas and track the progress of the team as a whole. However, we need to move a lot of technical discussions to GitHub. There will be a duplication of some tasks between Trello and GitHub. However, it is worth the effort. 

Currently, the friction of documenting on Trello and implementing in GitHub is causing Bloated Pull Requests with undefined scope, Duplication of effort, Lost Code, Conflicts between branches, and wasted efforts.

**Comment by theecrit** [comment]
Let's have an in-person conversation about this at the next Hack Night. Some of these open issues seem to require design before technical implementation is feasible (unless you want a bunch of technical rework once design is finalized after the fact). 

Now, if _implementing_ the navigation doesn't require making decisions about things like interface labels and IA (ie it's implementing back-end functionality, not front-end UI), then it makes sense to me to go straight to Github.

Alternatively, if you're not willing to consider that as an option, then we will need to define some very clear QA rules for design and some very clear rules for when something is considered "shippable."

**Comment by Ethan-bradley** [comment]
Here is the foundation template for a navigation bar: https://www.tutorialspoint.com/foundation/foundation_navigation.htm

**Comment by theecrit** [comment]
While we won't be doing mega menus, this is a great article about accessible menus in general: https://www.levelaccess.com/challenges-mega-menus-standard-menus-make-accessible/

**Comment by TangoYankee** [comment]
This issue turned into mostly a discussion on workflow. To preserve it, I'm going to rename it and close it. Anything related to navigation, I'll transfer into a new Issue for the Navigation bar.
