### ISSUE TITLE
Add "beta" notice in the UI that data may not be accurate

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#325]
## Description

If we're launching a live MVP site without account sign-in, we can't limit who uploads data. While it's highly unlikely anyone will upload non-WOEIP data given the fairly strict system requirements for file recognition, it would be irresponsible not to contextualize the data views. 

### Recommended solution

- [ ] Apply a yellow `dismissable block message` ([reference](https://semantic-ui.com/collections/message.html#dismissable-block)) to the View Maps and Upload Data pages.
- [ ] Message should be placed above global nav. 
- [ ] Message text: "WOAQ is currently in early release. You may encounter bugs and data may not be displayed accurately."

**Comment by theecrit** [comment]
@kbrdsk Assigned this to you, as I see you opened #341 to address it. :)

**Comment by kbrdsk** [comment]
> @kbrdsk Assigned this to you, as I see you opened #341 to address it. :)

Thanks! Sorry for not updating it
