### ISSUE TITLE
As a developer, I would like the links to files in the database to use the same protocol as the rest of the environment

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#329]
**Describe the bug**
The database returns a path to download a collection file that is hard-coded with `http`. As the production environment uses `https`, then requesting the link results in an ["mixed content"](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) warning. 

**Expected behavior**
The website is able to change the protocol based on environment.

**Additional context**
The `REACT_APP_PROTOCOL` client-side env variable provides the correct protocol for the environment.

**Labels**
- [x] Add a status label
  - `needs definition`
  - `needs help`
  - `ready to work on`
  - `in progress`
  - `backlog`
- [x] Add a `bug` label
- [x] Add additional labels as needed

**Affected Components (For Developers)**
`web/components/map/index`

**Comment by turnerhayes** [comment]
Could you use [protocol-relative URLs](https://en.m.wikipedia.org/wiki/Uniform_Resource_Locator#prurl) for this?
