### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#33]
**Is your feature request related to a problem? Please describe.**
A footer which navigates to external websites

**Describe the solution you'd like**
- It should contain links to the websites of affiliated websites, displayed only with text (no logos)
- It should respond to screen size

**Describe alternatives you've considered**
Considered using logos. However, this may confuse some users as to where the links go.

**Additional context**
The footer should be easy to read. It should be clear to the user what clicking on a link will do.

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
- File Structure:
  - file dedicated to the footer, labeled `_footer.html`
  - file is located in the `includes` folder
  - `_footer.html` is "included" in the `__base.html` file, just above the javascript `<script>` tags

**Technical Resources**
Video on [responsive footers built with Zurb](https://foundation.zurb.com/learn/building-a-responsive-footer-with-foundation-6-gary-jenning.html)

**Design Documentation**
- Look and Behavior:
  - ~~The footer should be thin~~
  - It should sticky to the bottom, when the page content is too short to fill the whole page
  - It should be pushed to the bottom of the page, and off screen, when the page content goes beyond the screen size
  - ~~On wide screens, such as laptops and landscape oriented phones, the text should be inline horizontally.~~
  - ~~On narrow screens, such as portrait-oriented phones, the text should stack vertically~~
 - Follow Figma Parent File Styling -TY 12 Aug 2020
- The displayed text and associated links are: 
  - **WOEIP**, `https://www.woeip.org/`
  - **OpenOakland**, `https://openoakland.org/`
  - **GitHub**, `https://github.com/openoakland/woeip`

- Wireframes
[WOAQ-wires-footer-20190326.pdf](https://github.com/openoakland/woeip/files/3011275/WOAQ-wires-footer-20190326.pdf)

**Comment by theecrit** [comment]
Can we label this as backlogged (not mvp), or is there a compeling reason this should be considered for MVP?

**Comment by TangoYankee** [comment]
[Zurb Tutorial on Footers](https://foundation.zurb.com/learn/building-a-responsive-footer-with-foundation-6-gary-jenning.html)

**Comment by TangoYankee** [comment]
- The footer should be thin
- It should sticky to the bottom, when the page content is too short to fill the whole page
- It should be pushed to the bottom of the page, and off screen, when the page content goes beyond the screen size
- It will only be links to affiliated websites
- The displayed text and associated links are:
  - **WOEIP**, `woiep.org`
  - **OpenOakland**, `openoakland.org`
  - **GitHub**, `github.com/openoakland/woeip`
- The text will be `inline block`
- File Structure:
  - file dedicated to the footer, labeled `_footer.html`
  - file is located in the `includes` folder
  - `_footer.html` is "included" in the `__base.html` file, just above the javascript tags

**Comment by TangoYankee** [comment]
> Can we label this as backlogged (not mvp), or is there a compeling reason this should be considered for MVP?

The updated label and issue description reflects a discussion at the 19 Mar 2019 OpenOakland hack night

**Comment by TangoYankee** [comment]
While we discuss the database, I took the downtime to work on the footer. It's not mobile friendly. But, it's a start. Check it out and let me know what you think. Branch: [footer](https://github.com/openoakland/woeip/tree/footer)

![WOAQ Footer 02 July](https://user-images.githubusercontent.com/11068062/60558495-4ed94980-9cfe-11e9-9e0f-e6eca1d02c3d.png)

**Comment by TangoYankee** [comment]
I believe OpenOakland is stylized as one word, in Upper Camel Case
