### ISSUE TITLE
https://woaq.org/ is down

### ISSUE THREAD

**Issue by abitrolly** [openoakland/woeip#339]
1. Go to https://woaq.org/
...

Is there any status monitor for OpenOakland?

**Comment by theecrit** [comment]
Hi @abitrolly, thanks for reporting this! We originally had the URL forwarding to this repo but have been working on configuring it to house the livewire branch via a semi-automated deployment flow. 

@ontoneio and @TangoYankee have been troubleshooting.

**Comment by TangoYankee** [comment]
To clarify, the website is functioning. It is the redirect from `https://woaq.org` to `https://www.woaq.org` that is malfunctioning.

The site can be reached at the later domain :)

**Comment by abitrolly** [comment]
Looks like https://woaq.org/ is hosted by Netlify and https://www.woaq.org/ is on Digital Ocean. Is it the case?

**Comment by theecrit** [comment]
Both URLs are working now, so closing this issue.
