### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#34]
**Is your feature request related to a problem? Please describe.**
The website needs a page to occupy the base (`/`) url. 

**Describe the solution you'd like**
 ~*TODO*: Design a simple, text only landing page. @theecrit, could this just be:~
> ~**Welcome to WOAQ**~
~West Oakland Air Quality (WOAQ) puts local air quality data in the hands of West Oaklanders~

[Updated 3/26/19] Content requirements should be dictated by project positioning and core user need. When we're ready to pick up this issue, I recommend we start from the [Core Model](https://alistapart.com/article/the-core-model-designing-inside-out-for-better-results) approach, something I've used to help keep pages focused and avoid too much Subjective Stakeholder Shiny Object Syndrome™ (not that we'd ever have such a problem).

- With this implementation, we'll also need to remove existing redirect of /index to /upload.

**Describe alternatives you've considered**
The previous design had the home page dedication to the login functionality. This goes 'against the grain' of the Django built-in authorization module. While it would be possible to modify the Django module for authorization, it would be time intensive and could generate bugs.

**Additional context**
- We are waiting to implement Accessibility related features
- Styling should be done mostly done using functionality built into foundation
- Dimensions of the content should be responsive to screen size.

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
- `./woeip/templates/index.html`

**Technical Resources**
[Zurb Documentation](https://foundation.zurb.com/sites/docs/)

**Design Documentation**
@theecrit, please link to updated wireframes
[Home page structure](https://trello.com/c/7YVHgY75/83-structure-of-home-page) Trello Card

**Comment by theecrit** [comment]
Is this a landing page for Github, or for our end users (WOEIP)/the product itself? If the latter, I'd prefer to open a design card for this in Trello first, then move it to a Github Issue once it's fully defined. Does that make sense from a workflow perspective?

**Comment by theecrit** [comment]
Adding a backlog tag to this per 3/5 hack night discussion: current sign-in page will serve as landing page for MVP.

**Comment by TangoYankee** [comment]
The wireframes originally had the sign in and homepage as the same function. However, the builtin Django Authorization package is designed to have a page dedicated to logging in. Consequently, for the MVP, we will have a separate landing page.

**Comment by TangoYankee** [comment]
For MVP, the url for home page will redirect to the login page.

**Comment by theecrit** [comment]
Quick tweak to issue description, since needs will change by the time we're ready to work on this.

**Comment by TangoYankee** [comment]
>  Subjective Stakeholder Shiny Object Syndrome™ 

So Shiny!

**Comment by theecrit** [comment]
Need to decide how to handle this now that account sign-in is likely post-MVP.

**Comment by theecrit** [comment]
Addressed with creation of home page at root.
