### ISSUE TITLE
UI adjustments on Upload Confirmation screen

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#358]
## Description

When we moved to Create React App, all the components (form fields, labels) on the Upload Confirmation page became centered and the order got switched up. We want to bring them back to parity with wireframes. 

### Acceptance criteria
- [ ] Components are left-aligned
- [ ] Field labels appear above or to the left of inputs
- [ ] Inline validation components appear to the right of or below inputs

### References
- Figma [wireframes](https://www.figma.com/file/VamJMrwAcSJGFfDIi1xLLa/WOAQ-Data-Flow-Copy?node-id=0%3A1) (see "5 - confirmation")

**Comment by exchrotek** [comment]
Niels met with Jonathan and they talked about using plugins/tools. Niels looked into Overlay plugin for Figma, which allows a lot of the front end designed in Figma to be translated to React JS code.

**Comment by theecrit** [comment]
FYI this is a dev issue, not a design issue. The designs are done (the linked wires). I may revamp the labels to make those distinctions more clear.

**Comment by theecrit** [comment]
Updated wireframes to correct file!
