### ISSUE TITLE
Style data points on the map via MapBox API

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#365]
## Description
Style data points on the map according to rules in #237.

## Success criteria
- [ ] TBD

## Dependencies
- Requires completion of #366 first.

**Comment by exchrotek** [comment]
@kwonangela7  to break down further in the next sprint. Some of the sub-tasks that result may require pair programming.

**Comment by kwonangela7** [comment]
I'm closing this ticket as it's essentially a duplicate of #237
