### ISSUE TITLE
Prepare MapBox styles for customization

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#366]
## Description
This issue covers prep work to enable non-React styling directly via MapBox API.

## Success criteria
- [x] Brooks' MapBox styling is publicly available
- [x] Angela can access styling in MapBox

### Dependencies
- Need to identify if more work is needed on PR #364 in order to complete this issue
- This issue needs to be completed for #237 to be considered complete
- This issue needs to be completed for #365 to be considered complete

**Comment by kwonangela7** [comment]
Kabirdas' [PR](https://github.com/openoakland/woeip/pull/364) is complete; it just needs an approving review. The only dependency for this ticket to be complete has been fulfilled ✅

**Comment by kwonangela7** [comment]
I'm able to access Brooks' [style](https://api.mapbox.com/styles/v1/bjessup/ckooyp5jf1e0717p6ojtjol3d.html?fresh=true&title=copy&access_token=pk.eyJ1IjoiYmplc3N1cCIsImEiOiJja29hdThpMW0wNTB0Mm5va3hiMTg3MDg4In0.cOpsPQrnbE5-k05WMtLvog#9/37.78/-122.4241) publicly, but there's some error copying it over to my account that I just asked Brooks and Kabirdas about. I think we can consider this ticket closed though.

**Comment by exchrotek** [comment]
@theecrit ready for your review, as all the acceptance criteria have been. This is from sprint ending on 9/27
