### ISSUE TITLE
Update content and respective global nav options

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#374]
## Description

The current global navigation includes links to `About`, `Upload`, and `Maps`. These options need to be updated to reflect the MVP information architecture.

### Acceptance criteria
- [x] New pages created for:
  - [x] West Oakland's Air
  - [ ] ~Get Involved (@theecrit to update content)~
- [x] Global nav includes the following options with functional links to the appropriate pages:
  - [x] West Oakland's Air
  - [x] Upload Data
  - [x] View Maps
  - [x] About us

### Dependencies and other considerations
- Dependent on completion of #246 
- Content for "West Oakland's Air" and "Get Involved" page: https://docs.google.com/document/d/1iBKiQjxV_n5qQuHQLAfsX1r5mIDKn9-ggksfDwkkx4g/edit?usp=sharing

**Comment by gsehrlich** [comment]
(Edited) Just checked some boxes. Do we still want "West Oakland's Air" in MVP?

**Comment by theecrit** [comment]
@gsehrlich I've got a branch going locally and have managed to create the pages and update the nav menu. But I'm having trouble with the `export const {page-name} = () => (` on line 4 of the `index.js` file — I'm not sure what to replace {page-name} with to get the content container to display.

**Comment by gsehrlich** [comment]
Oh nice! Whatever you replace `{page-name}` with will be the variable you use to render the component. For example, in web/src/components/home, it's called `Home`. Then, in web/src/components/nav/switch.js, you need to import it and add it like the other pages. Let me know if that works!

**Comment by theecrit** [comment]
I think I'm having trouble with the apostrophe in "West Oakland's Air" — I've tried all of the following approaches to no avail:

`'West Oakland's Air'`
`"West Oakland's Air"`
`West Oakland\'s Air`
`"West Oakland\'s Air"`
`'West Oakland\'s Air'`

ETA: and also `west-oaklands-air`, which is the assigned slug in `bar.js`.
`

**Comment by gsehrlich** [comment]
I’d suggest `WestOaklandsAir`. It doesn’t have to match the actual title;
you just need to refer back to it in switch.js. But it does have to follow
javascript variable naming conventions.

**Comment by theecrit** [comment]
Oh, derp! I completely missed updating `switch.js`. Thank you, worked a treat!
