### ISSUE TITLE
Typo in error message when selecting a single file to upload

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#375]
**Describe the bug**
The word "cvs" should read "csv" in the error displayed when user uploads only a single file.

**To Reproduce**
1. Select "Upload" from global nav
2. Select a file from the finder
3. Observe typo in warning displayed

**Expected behavior**
The file type should be described as a "csv" not a "cvs"

** System info **
 - Device: MacBook Pro
 - OS: 10.15.7
 - Browser: Firefox 93.0

**Comment by exchrotek** [comment]
Fixed "cvs" to "csv". Opened a new PR
