### ISSUE TITLE
[BLOCKED] API Request URL is incorrect. Needs to be updated with Environment variable

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#376]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="800" alt="Screen Shot 2021-10-12 at 10 42 14 PM" src="https://user-images.githubusercontent.com/32755410/137066229-60f693fd-a9bf-4b26-8ddb-8a00e3e85792.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by ontoneio** [comment]
Currently the site deploys from the main branch. The reason for the error is because the request is being sent to an incorrect API url. It's an environment variable that needs to be fixed.

**Comment by ontoneio** [comment]
![image](https://user-images.githubusercontent.com/24515434/137542684-4b112e6f-2d21-474f-a7e5-31e3daa631fc.png)

**Comment by TangoYankee** [comment]
The variables is incorrect on the [`main`](https://github.com/openoakland/woeip/blob/main/web/.env.production) branch but correct on the [`develop`](https://github.com/openoakland/woeip/blob/develop/web/.env.production) branch. There should be no new code required to fix this. We should be able to push `develop` to `main` and that should resolve the issue. @wendy-wm-wu @theecrit @ontoneio

**Comment by exchrotek** [comment]
- [ ] push develop to main

**Comment by exchrotek** [comment]
Jonathan said there was some chatter about moving away netlify since it might not be useful anymore? However, Tim wants the netlify repo to be transferred over to an OpenOakland account (away from Jonathan's personal) and we will continue to try to integrate it.

This issue is BLOCKED until netlify integration is complete.

**Comment by theecrit** [comment]
Fixed.
