### ISSUE TITLE
[RISK] What is WOEIP's plan to sustain collection of data?

### ISSUE THREAD

**Issue by exchrotek** [openoakland/woeip#418]
How was WOEIP able to convince people to volunteer to collect data with the Dustrak? Is this something that they can sustain over time? 

Is it fair to say that the viability of our app is largely dependent on WOEIP's success with the volunteer effort? Because we are essentially building a product that relies heavily on volunteer effort, we may need to even start thinking about how we can improve participation.

**Comment by exchrotek** [comment]
I wonder if there's any merit to us trying to form a partnership with Habitat for Humanity or Youth Spirit Artworks, both nonprofits in Oakland, to organically increase volunteers for this cause. I don't know how big of an effort this would be though for OpenOakland to reach out to the other 2 groups to form some partnership. 

As an aside, in general I think it'd be a super cool idea for OpenOakland as a whole (not just the WOAQ group) to work with them and be able to solve any software needs they may have to help multiply their impact on the community.

@theecrit @hawser what do you think?

**Comment by theecrit** [comment]
Our goal isn't to manage WOEIP's volunteer program so I would be hesitant to focus our efforts there. Our focus has been to provide the tooling to support our partner's work. They have a program and don't generally have problems recruiting volunteers for data collection. Their need is the tech infrastructure. 

More broadly, they do have staffing needs and we could conceivably provide some consultation support to help them define those needs as they relate to digital strategy but they have other strategic focuses first, from what I understand.

**Comment by exchrotek** [comment]
Good to know! Then it seems like this risk is nonexistent then!

**Comment by exchrotek** [comment]
@hawser  Hey niels, before I close this issue and consider it resolved, I wanted to give you a chance to chime in! Did you have any thoughts or comments about this issue?

**Comment by hawser** [comment]
@theecrit has a more current understanding of what is going on at WOEIP and I would agree with what she has said. I would say that it is a great idea to get an understanding on how to increase and retain volunteers, because it would  be helpful for OpenOakland, that is a larger question that your question has implied.
