### ISSUE TITLE
As a user, I would like the website to automatically know about my data

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#43]
**Is your feature request related to a problem? Please describe.**
Information about the dataset is available in the uploaded files. I would like the website to look through the files and automatically extract the data.

**Describe the solution you'd like**
A script that parses the data from the files and places it in a staging table

**Describe alternatives you've considered**
An alternative design requires all of the data to be manually inputted by the user.

**Additional context**
This script comes after the upload process. It accesses the files, after they have already been placed in an S3 bucket/folder. The parsed data is placed in a staging table. This issue comes before the page where the data values are confirmed by the user.

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
List what pages or backend files will need to be added, removed, or changed

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
Wireframes or other design resources

Discuss the how data session will acquire information about the sensors that were used in data collection.

Initial TODOs:
`forms.py`
>  TODO: Include Sensor fields that are seen by client when uploading the files.
> 1) It is more transparent to the user what data is being loaded and why.
> 2) It is easier to generalize the website, once other sensors are available.

`views.py`
> TODO: Include Sensor fields that are seen by client when uploading the files.
> 1) It is more transparent to the user what data is being loaded and why.
> 2) It is easier to generalize the website, once other sensors are available.
> TODO: Rather than hardcode the value of the Sensors, present it as an option in
> the form the client sees. However, have it pre-filled with the pre-loaded objects
> of Dustrak and GPS. This will also achieve the goal of outsourcing some of the
> view code to other modules. ie) The object call will be done in the form, instead

**Comment by TangoYankee** [comment]
@r-b-g-b This script works with the [Javacript Upload Form](https://github.com/openoakland/woeip/issues/31) to automatically [pull fields](https://github.com/openoakland/woeip/issues/63#issuecomment-472693978) for the database. Could you and @Ethan-bradley work together to ensure that your *django upload script* and his *javascript drag and drop* functionality will work together? 

Write your key code requirements in the issues. That way, they are clarified and recorded for each other. Also, other developers can pick up where you left off, if you're unable to finish the implementation because of other obligations.

They should still be separate PRs. However, I understand if you need to combine them into one PR to get a functioning product.

**Comment by theecrit** [comment]
Quick tangential question/clarification triggered by the views.py TODO above. Understanding that it's not fair to assume anything, is it fair to assume that the editable field is only editable to properly authenticated users within the upload confirmation flow? In other words, when non-authenticated/permissioned users are viewing a map, fields should not be editable.

**Comment by TangoYankee** [comment]
@theecrit Correct. We manage this by splitting what a `view` can do to a database. `views` can have a mix of read, write, edit, and delete rights. In HTTP terms, these capabilities are "methods" called `GET`, `POST`, `PUT`, and `DELETE`. Editable fields are contained in `views` with `PUT` or `POST` capability. Only logged in users can even access these `views`. Unauthorized users will be redirected to a login page. Generally, each web page has its own `view`

Uploading the data will be a `view` with `POST` capabilities that can only be accessed by authorized users. It might help to comment on the wireframes with the HTTP methods each page can execute.

**Comment by theecrit** [comment]
Got it. So would that mean we'd need a view for the "View Maps" page with only the `get` capability, if we want non-logged in users to be able to view that page without being able to edit it? And would that require redundant work (and if so, is there a more efficient alternative)?

**Comment by TangoYankee** [comment]
@ifed3 I started looking into a more detailed overview of how this issue could be implemented. Based on the currently open [data upload PR](https://github.com/openoakland/woeip/pull/109), I was able to get a much better understanding.

It seems that we don't need a 'staging table'. We can simply set the 'initial values' of the `ConfirmForm`. The user can choose to keep or change these values. Once the form is submitted, values can be sent to the database, as well as the air quality readings.

There are lot of details to this implementation. Because pylint triggers an error for the location of each `TODO`, I used this to my advantage. My proposed steps to implementation are in the codebase, prefaced with `TODOs`. You can find them by running `make quality` (within `make local.shell`).  The branch is [ty/confirm-metadata](https://github.com/openoakland/woeip/tree/ty/confirm-metadata)

Of course, these are just my suggestions. Whatever the team thinks is best!

As an aside, I also changed how the navigation behaves on small and medium screens. I understand this goes against the proper the workflow, by working on an issue unrelated to the primary issue. But, I found the current behavior distracting. It also took about 5 min to change. I apologize profusely but regret nothing. ¯\_(ツ)_/¯

**Edit**: Looking forward, it seems this branch also covers about 85% of Issues #88, #89, #90. It also covers a yet-to-be defined issue where the data is actually uploaded to the database. I'm not sure whether this is a reflection of poor coding or poor issue scoping. However, I did want to bring it to the attention of the team.

**Comment by theecrit** [comment]
**Re: staging table**
@nbilenko, @r-b-g-b, and I chatted about this last night, and came to a similar conclusion. Natalia's proposal was to flag the data as "unvalidated" or similar, and remove the flag when the user confirms. I'll let them pipe in with any clarifications/additional thoughts.

**Re: navigation**
Been meaning to check this out and will do so before end of the week. Is this change treated as a separate branch? Or should it be? 

**Re: #88, #89, #90 and issue-writing**
Yeah, our current issues are not scoped well, IMO. This is in large part due to not deliberately/methodically translating the original requirements into properly-scoped Issues. See my update in the Slack channel for context/proposed fix. Basically, we have a set of original requirements that was never truly finalized and translated:
<img width="1415" alt="Screen Shot 2019-06-19 at 8 38 11 PM" src="https://user-images.githubusercontent.com/32755410/59816847-81348100-92d2-11e9-88ca-927e499fbb4e.png">

I think we can do better, and hope to have a proposed draft of new Issues scoped (not fully written, mind you), by next Hack Night.

*Edited to add:* Whatever we decide about the staging table, one principle needs to be honored, which is that we must keep an unedited version of the raw files on the server for posterity (in case anyone down the line ever needs to work with or review the raw data; e.g. we want to be able to preserve an unadulterated data set on the server).

**Comment by theecrit** [comment]
My preference is to *not* move data directly into the main table until the user has confirmed their details. I'd be interested to hear y'all's thoughts on the staging table vs. panda dataFrame, per:

![WOAQ-Data-Flow-Diagram-v3](https://user-images.githubusercontent.com/32755410/59968365-9b967680-94ed-11e9-982a-6ac628e7f079.png)

**Comment by theecrit** [comment]
Resolved.
