### ISSUE TITLE
Format Data Entries

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#44]
Guide the user to the correct data format on data entry.

**Comment by TangoYankee** [comment]
Current TODO from ty/files-upload
`form.py`
> TODO: On the client side, create an inteface to guide the user to the
> correct date format

**Comment by theecrit** [comment]
A cursory search led me to this Foundation-based date picker: http://foundation-datepicker.peterbeno.com/

Once I get the uploader installed locally, I’ll create wireframe for the upload screen and attach it here.

**Comment by nbilenko** [comment]
Feature is unnecessary because the date collected can be retrieved from the data file.
