### ISSUE TITLE
When hovering over a dot near the map's border, I'd like to the pop-up to appear fully within the map frame

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#442]
**Is your feature request related to a problem? Please describe.**
Currently when I hover over the map near the edge, the data pop-up gets cut off by the frame and I can't view the whole thing.

**Describe the solution you'd like**
I'd like to be able to view the entire pop-up. One approach would be to detect which edge the pop-up is near and pop it up to either the right or left, depending on position.

**Describe alternatives you've considered**
We could try to display the pop-up over the extended edge of the map but that may be tough to do technically? 

**Screenshot
![Screen Shot 2022-04-01 at 3 05 15 PM](https://user-images.githubusercontent.com/32755410/161352556-dcf93b53-f310-4340-9c7f-0c29969415ac.png)
**

**Comment by TangoYankee** [comment]
To achieve the left/right detection, attach a [element refs](https://learnreact.design/posts/react-useref-by-example) to the mapbox and the hover panel. Then, get their dimensions using `getBoundingClientRect`. 

To make the hoverpanel appear over the whole page: first, try giving it a z-index. If that doesn't work, Move it from being nested in the box and instead place it higher it in the DOM.

**Comment by gsehrlich** [comment]
For a different issue ( the last piece of #331), I switched the hover implementation to use a react-map-gl element called Popup, which has the desired behavior by default. I'll reference this issue in the PR.

**Comment by theecrit** [comment]
@gsehrlich  Amazing, thanks!
