### ISSUE TITLE
Update header with new logo

### ISSUE THREAD

**Issue by gsehrlich** [openoakland/woeip#458]
@francesnadine has designed a new logo that needs to be put on the website.

**Labels**
- [x] Add a status label
  - `needs definition`
  - `needs help`
  - `ready to work on`
  - `in progress`
  - `backlog`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
Not sure

**Design Documentation**
Ask @gsehrlich or @francesnadine for the SVG or JPEG.

**Comment by theecrit** [comment]
Can someone attach the image file to this issue? Thanks!

**Comment by gsehrlich** [comment]
SVG:
![woaq logo](https://user-images.githubusercontent.com/11000354/165132339-3f5af08d-bca3-4dd0-8b27-1229d1d8aeae.svg)
JPG:
![woaq logo](https://user-images.githubusercontent.com/11000354/165132347-505dd5be-e39a-4881-9c7d-aa2dde89b262.jpg)
