### ISSUE TITLE
"Files match" message when files don't match

### ISSUE THREAD

**Issue by gsehrlich** [openoakland/woeip#460]
**Describe the bug**
Arbitrary pairs of files will trigger a "Success! Your files match"  message.

**To Reproduce**
1. Go to "Upload"
2. Create two blank text files
3. Drag and drop both into the upload field
4. See success message

**Expected behavior**
The files are rejected with a "Files don't match" message or a "Neither file is in a GPS or DusTrak format" message.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version 1.37.116 Chromium: 100.0.4896.127

**Labels**
- [x] Add a status label
  - `needs definition`
  - `needs help`
  - `ready to work on`
  - `in progress`
  - `backlog`
- [x] Add a `bug` label
- [x] Add additional labels as needed

**Comment by theecrit** [comment]
Seems like the checks being run aren't catching file format. We have an error message for that in the wires.
