### ISSUE TITLE
Views Testing

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#58]
**Is your feature request related to a problem? Please describe.**
Views Testing

**Describe the solution you'd like**
Create tests to check whether views are accomplishing their intended design

**Additional context**
Previous task that must be completed: Finalize functionality of views
[Views Testing Documentation](https://django-testing-docs.readthedocs.io/en/latest/views.html)

**Comment by nbilenko** [comment]
Closing this issue b/c it's no longer relevant.
