### ISSUE TITLE
Forms Testing

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#59]
**Is your feature request related to a problem? Please describe.**
Forms Testing

**Describe the solution you'd like**
Create test cases to validate design of Forms meet intended use cases

**Additional context**
- Before beginning this task, the design of the forms must be finalized
- Addressed in PR #57 

[Django Forms Testing Documentation](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing)

**Comment by nbilenko** [comment]
Closing this issue b/c it's no longer relevant.
