### ISSUE TITLE
As a data uploader, I want to verify the information I've uploaded to the system.

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#63]
**Is your feature request related to a problem? Please describe.**
Currently, the system automatically pairs uploaded csv and log files based on the data within the files. We want to make sure the system has gotten it right, provide the user with an opportunity to make corrections, and request additional data from the user that the system can't collect from the files themselves. 

**Describe the solution you'd like**
A form-based UI with the following functionality:
* Confirmation message (notification/alert bar) that indicates if file upload was successful and provides feedback about what took place.
* Form containing fieldsets for as many sessions as were uploaded
* Within each fieldset:
  * Date field (pre-populated w/ session date pulled from file), including date picker to ensure formatting
  * Start time field, pre-populated with extracted start time, including time picker to ensure formatting
  * ~End time field, pre-populated with extracted end time, including time picker to ensure formatting~ *descoped*
  * Device field, pre-populated with device name extracted from file and matched to DB
  * Collected By field, pre-populated based on logged-in user name (type-ahead input should suggest name based registered users, potentially revealing a drop-down or other list style alphabetized by first name...see [example](https://developer.salesforce.com/blogs/developer-relations/2015/06/salesforce-lightning-inputlookup-missing-component.html)).

**Additional considerations/use cases:**
* **Uploading multiple sessions at once:** If sessions reflect different routes, start and end times are more easily identified. If multiple sessions are uploaded from the same route, we need to figure out how to define start/end time.
* **Accessibility:** Identify which [WCAG guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/glance/) apply, and define a plan to implement them 

**Describe alternatives you've considered**
Investigated placing manual field entry on same screen as drop zone but felt it was better to get the user into the upload flow as quickly as possible (lower the barrier to entry), and present manual data entry as part of a confirmation experience so it feels a little more rewarding. UI also gets clunky if it's added to the drop zone screen.

**Additional context**
n/a (see flow under _Design Documentation_)

**Labels**
- [X] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [X] Add additional labels as needed

### For Developers
**Affected Components**
List what pages or backend files will need to be added, removed, or changed

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
See "Data Confirmation" wireframe: [WOEIP-UploadFlow-v3.pdf](https://github.com/openoakland/woeip/files/2959738/WOEIP-UploadFlow-v3.pdf)

Edit by Tim: Formatted fields as sub-list, to differentiate

**Comment by TangoYankee** [comment]
- Fields:
  - `Date` and `Start` time will be combined and stored in the database as a `Datetime` in the field `date_collected` in the `session` model. They will be sourced from the `dustrak` file
  - The database does not track an `End Time`. It should be removed from the form.
  - `Device Information` is sourced from `dustrak` file
  - In `form` jargon, the `default` value for `collected_by` is the currently authenticated `user`. The user can change this value by typing. As the user types, the `form` will make suggestions from a list of `users` pulled from the Django database.
  - `Routes` are not part of the MVP. The `route` key in the `session` model will be null for this implementation
  - `Sensor` see question below

**Additional use cases**
1. Multiple sessions: Currently out of scope of the MVP
2. Accessibility involves properly labeling `html` tags and creating well designed css. The html tags are within the scope of this PR and the html should adhere to accessibility standards. Any css should be saved for later iterations. [Section 508 Resources](https://github.com/TravisSpark/spark-website/wiki/Support-Services#section-508-compliance)

Question
 - The `Sensor` model contains the field `units`. @r-b-g-b, can `units` be automatically pulled from the `dustrak` file?

**Thoughts on Implementation**
- I'll need to resume this another time. But looking at the scope of this issue, it seems to need to be broken into smaller pieces for implementation. Off the top of my head:
  - The navigation bar
  - The javascript to drag and drop files
  - The javascript to add the *fading* success message.
  - the upload `form`, `view`, and `template` (Will send a `POST` request to create session. Url: `session/upload` change from `files/upload`)
  - the data confirmation `form`, `view`, and `template` (Will send a `PUT` request to edit session. Url: `session/confirm`)
  - tests for the Django Views
  - tests for the Django Forms
  - A python script to parse the dustrak data
  - A test that the dustrak data was correctly parsed

**Comment by theecrit** [comment]
Hi Tim,

While HTML and css implementation cover many a11y issues, best practices go well beyond that and impact UX and content, as well as code structure. Section 508 requires WCAG 2.0 compliance. However, CA law requires compliance with “Web Content Accessibility Guidelines 2.0, or a subsequent version” (at the AA level)[source](https://www.dor.ca.gov/Home/AB434). WCAG 2.1 was released mid-last year and is additive to 2.0, to account for many digital realities not originally accounted for in 2.0. All of it is in service of four core principles: making the product *perceivable*, *operable*, *understandable*, and *robust*.

Per my comment, this may be prohibitive for an MVP launch, so it’s worth proactively coming up with a plan to reach some baseline standards. I’m looking into whether C4A has any specific standards, but in the meantime there are lots of great resources out there to help us (including the [WCAG quick reference guide](https://www.w3.org/WAI/WCAG21/quickref/)). I’ll create a new Issue where we can have a dedicated discussion independent of this specific page implementation. In the interim, I’ll keep the a11y note in the Issue as-is until we can specific what's required for this specific screen.

Regarding your de-scoping of multiple files: This is fine with me but going forward, if someone wants something de-scoped, lets talk about it as a team. I’ll commit to the same.

Thanks,
J.

**Comment by theecrit** [comment]
@TangoYankee Re: implementation — this Issue is specific to the *confirmation* page only, not the entire upload flow. Bear that in mind regarding your implementation notes.

Also, re: the confirmation message—we need to think about what the system will allow and, therefore, where errors may occur that impact messaging. 

### Use cases
What happens when:
* The user drag-and-drops multiple of each? 
* The user drag-and-drops only one file? 
* The user drag-and-drops the wrong files? 
* The system doesn't detect a matching pair?

Am I missing any?

**Comment by TangoYankee** [comment]
@theecrit this Issue may be related to confirmation. However, it is dependent on the parts on listed above. Not all of these dependencies have been implemented or had issues opened. I created the list here, so that we can track the progress of open and addressing these prerequisite issues.

For the uses case, I am sure there will always be more. But, we've hit enough for a viable product.

**Comment by theecrit** [comment]
@TangoYankee Let's plan to write the outstanding related Issues tomorrow night? Assuming you'll be there, that is.

**Comment by TangoYankee** [comment]
I had a thought about timezone. If we are saving the data to the database before allowing the user to confirm the data, then the dates will have already been converted from local to UTC time in the database. If the user changes the local time, then we will need to go through and change the time of every data point in the database. 

This is probably an argument for not uploading all the data to the database. The files are saved to the S3 bucket. So the data is safe. We could:
- The `session/new` view will upload the files to the S3 bucket
- The location and id of the files will be saved
- The `session/new` view will pass the file location/ids to the `session/[id]/confirm` view (name TBD)
- The `session/confirm` view will call a function that will open the desired file and parse through it for meta data.
- The parsed data will be sent to the form as the default values
- This parsed data will be complemented by preset time zone and a `collected_by` field generated by the name of the logged in user
- The user will edit and save the data as they need
- If the user saves the data, it will be sent to the database
- If the user cancels the process, the uploaded files and associated database entry will be removed. 
  - This will require a confirm button

If want to save to the database first, we could make the timezone a field on the original upload form. While we're at it, might as well include the `collected_by` field too.

[Status of data](https://trello.com/c/0ZEkmsRk/90-status-of-data-during-verification-step) Trello Card

**Comment by TangoYankee** [comment]
I split this topic into three issues, each with the label `verify-page`

**Comment by theecrit** [comment]
Closing as covered via #88, #89, and #90
