### ISSUE TITLE
Implement session page

### ISSUE THREAD

**Issue by nbilenko** [openoakland/woeip#64]
Implement a skeleton session page with the session metadata.

Wireframe based on
https://trello.com/c/f81CfYp8/35-document-v2-ui-improvements-for-implementation

**Comment by theecrit** [comment]
~Is this meant to be different from #63?~ Nevermind, I see this is the map view page. Carry on.

**Comment by TangoYankee** [comment]
For the URL patterns, I opened a [URL mapping card](https://trello.com/c/pzgbHYU7/82-url-mapping) on Trello. That is the best place to discuss how we should structure our URLs.

**Comment by theecrit** [comment]
@TangoYankee How do you feel about adding a "blocked" label to this, to indicate it can't be worked on until a dependency is resolved?

**Comment by theecrit** [comment]
Assigning to myself temporarily to flesh out issue further. Then will reassign to next available dev.

**Comment by theecrit** [comment]
Closing as "won't fix" due to tech stack changes; now covered by issue #94.
