### ISSUE TITLE
Update WOEIP descriptions in README

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#67]
**Is your feature request related to a problem? Please describe.**
The current description of WOEIP and its activities aren't necessarily accurate, and haven't been vetted by WOEIP.

**Describe the solution you'd like**
* Under *Organizations:* 

Replace 
>West Oakland Environmental Indicators Project (WOEIP) is an environmental justice nonprofit. Their mission is to help residents understand and influence the political and natural forces which impact their lives. WOEIP's overall goal is to empower West Oakland residents to revitalize the environment and economy of their neighborhood.

with 
>The West Oakland Environmental Indicators Project is a resident led, community-based environmental justice organization dedicated to achieving healthy homes, healthy jobs and healthy neighborhoods for all who live, work, learn and play in West Oakland, California. Through our Community-Based Participatory Research projects and our Collaborative Problem-Solving Model we build community empowerment and help local residents to achieve their own vision for healthy neighborhoods.

(pulled from WOEIP website; pending confirmation from Brian).
* Under *Project Description:* 

replace 
>The current AQ database is difficult to interact with and manage.

 with
>The original AQ database is no longer accessible to WOEIP, leaving them without access to collected data. As a result, they've suspended their citizen scientist data collection program.

**Describe alternatives you've considered**
n/a

**Additional context**
It's important that we allow our project partners to speak with their own voice, and are intentional about considering this when writing or speaking about them.

### For Developers
**Affected Components**
README.rst

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
n/a

Edited to increase readability by swapping quotation marks with block quotes.

**Comment by TangoYankee** [comment]
I agree with the changes and the reason behind making them. I vote to move from `discussing` to `ready`.

**Comment by kiwisquash** [comment]
I can take this.

**Comment by TangoYankee** [comment]
@kiwisquash The PR is approved. Go ahead and merge it when you're ready.

**Comment by kiwisquash** [comment]
@TangoYankee I don't have write-access.

**Comment by TangoYankee** [comment]
@kiwisquash I merged. If you'd like to keep contributing, let me know. I'll give you write access.

**Comment by kiwisquash** [comment]
@TangoYankee Thanks for doing the merge. And yes, I would like to keep contributing.
