### ISSUE TITLE
Integrate Custom and Foundation CSS and Javascript

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#68]
**Is your feature request related to a problem? Please describe.**
The website needs to be organized and structured in a way that is beyond the capability of HTML.

**Describe the solution you'd like**
Integrate the Zurb Foundation CSS framework and files for custom css and js. For development, I would like to integrate Foundation using a CDN. The custom css and js would live in a file saved locally to the project. For production, the CDN would be exchanged for an a-la-carte download of all the components used in development

**Describe alternatives you've considered**
I considered downloading the whole framework. However, this would take more time to install. I also considered downloading each component as its needed. However, we aren't sure exactly which components we will need.

**Additional context**
CDNs are quick to integrate because it only requires one line of code to implement. However, they create vulnerabilities for production code. For example, the hosting site could experience an outage, the content could be updated and break compatibility with our site, or it could modified in a way that creates a security vulnerability. 

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
* Create an `app.css` file in a `./woeip/static/css/` folder
  * The name comes from Zurb's use of `app` in their demo of custom css
  * Even though it's currently a single file, I want to have a dedicated folder for when the css and js files have multiplied
* Create an `app.js` file in a `./woeip/static/js/` folder
* Place the [CSS CDN link](https://foundation.zurb.com/sites/docs/installation.html#cdn-links) and [custom CSS link](https://docs.djangoproject.com/en/2.1/howto/static-files/) in the [html head](https://www.w3schools.com/CSS/css_howto.asp), with the [Custom CSS after the CSS CDN](https://bootstrapbay.com/blog/customize-bootstrap)
* Place the corresponding javascript links just before the closing [`</body>` html tag](https://humanwhocodes.com/blog/2009/07/28/the-best-way-to-load-external-javascript/)

**Technical Resources**
[Zurb Foundation CDN](https://foundation.zurb.com/sites/docs/installation.html#cdn-links)
[Article on adding custom css to a framework](https://bootstrapbay.com/blog/customize-bootstrap/)
[Django Static Files](https://docs.djangoproject.com/en/2.1/howto/static-files/)
[*Human who codes* JS placement](https://humanwhocodes.com/blog/2009/07/28/the-best-way-to-load-external-javascript/)

**Design Documentation**
[Trello Card discussing CSS Frameworks](https://trello.com/c/XiuFNIer/62-select-ui-components)

**Comment by theecrit** [comment]
If I'm understanding this correctly, the idea is to host the components elsewhere while we're building, then once we're ready for production we pull everything to keep it hosted local to the app? Sorry, I'm using cludgy language, I know.

**Comment by TangoYankee** [comment]
Yes. And it's faster because someone is already hosting it. We just need to reference it.

**Comment by theecrit** [comment]
Word. Sounds good to me. Feel free to re-label from `discussing` to `ready` if you feel it's good to go.

**Comment by kepta** [comment]
Hey I might not have a lot of context, please let me know if my suggestion sounds out of scope. I was wondering if you have considered using [`gh-pages`](https://pages.github.com) as the CDN for the static assets?

**Comment by TangoYankee** [comment]
> For production, the CDN would be exchanged for an a-la-carte download of all the components used in development

Before launch, we'll move the assets from the CDN to the static folder in the project itself. The CDN is only for development. It's not really worth moving, as we'll stop using it soon.

**Comment by TangoYankee** [comment]
I assigned myself because I already have a prototype branch built. I'll make a PR tonight.

**Comment by TangoYankee** [comment]
Reopening issue because pull request has multiple errors related 
Errors:
- [x] Missing script to load JQuery
- [x] Missing `load script`
- [x] JS and CSS files still referenced as `custom` when name was refactored to `app`
- [x] Missing `%' from script for app js
- [x] Missing script to load foundation js
