### ISSUE TITLE
Mental Model for Contributing Doc

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#69]
**Is your feature request related to a problem? Please describe.**
The motivation of the contributing workflow is to help create a shared mental model of the code and its implementation. The contributing document fails to explicitly state this. This may lead to confusion over its intentions and a hesitation to follow its guidelines. I would like the motivation to be explained in the workflow.

**Describe the solution you'd like**
I would the **Issues** Section of `contributing.md` to explain the importance of shared mental models, with a link to the associated Medium Article

Proposed Explanation:
>Code for America attracts diverse developers with ephemeral tenures. (Maybe convey 'short stints' it in a less pretentious way?) This adds a breadth of knowledge that can greatly enhance a project. However, it also adds a layer of social complexity to an already technically complex project. By discussing the code in GitHub issues, we clarify a shared mental model of the code, outline pseudo-code, and pair program. We also document the design process and preserve it through several generations of developers. To learn more, read [Effective Mental Models for Code and Systems](https://medium.com/@copyconstruct/effective-mental-models-for-code-and-systems-7c55918f1b3e) by Cindy Sridharan.

**Describe alternatives you've considered**
A lack of explanation

**Additional context**

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
**Issues** section of `Contributing.md`

**Technical Resources**

**Design Documentation**
[Effective Mental Models for Code and Systems](https://medium.com/@copyconstruct/effective-mental-models-for-code-and-systems-7c55918f1b3e)

**Comment by theecrit** [comment]
I think this is great. What do you think of the following revision (primarily to the intro sentences)?

> The nature of Code for America projects (and open source in general) provides the opportunity to tap into an incredibly diverse pool of talent. This variety of skill sets, areas of expertise, worldviews, and lived experiences greatly enhances community-focused projects like WOAQ. However, it also adds a layer of social complexity to an already technically complex project. By discussing the code in GitHub issues, we vet our individual assumptions, clarify a shared mental model of the code, outline pseudo-code and other solutions, and pair program. We also document the design process and preserve it through several generations of developers. To learn more, read Effective Mental Models for Code and Systems by Cindy Sridharan.

**Comment by hawser** [comment]
I like the process introduced by Effective Mental Models for Code and Systems. For me, this project has demonstrated the value of reflection time and again. Think it through before action. I came up with an alternate to be considered, based on @theecrit  contribution but stripped down. Proposed:

Code for America attracts a diverse pool of talent. This diversity brings wide ranging skills, areas of expertise, and lived experiences to community-focused projects like WOAQ. However, it also adds a layer of social complexity to an already technically complex project. By discussing the code in GitHub issues, we clarify a shared mental model of the code, outline pseudo-code, and pair program. We also document the design process and preserve it through several generations of developers. To learn more, read Effective Mental Models for Code and Systems by Cindy Sridharan.

**Comment by hawser** [comment]
Discussed and updated. Proposed:

>Code for America projects and open source in general provide the opportunity to tap into an incredibly diverse pool of talent. This variety of skill sets, areas of expertise, world views, and lived experiences greatly enhances community-focused projects like WOAQ. However, it also adds a layer of social complexity to an already technically complex project. By discussing the code in GitHub issues, we vet our individual assumptions, clarify a shared mental model of the code, outline pseudo-code and other solutions, and pair program. We also document the design process and preserve it through several generations of developers. To learn more, read Effective Mental Models for Code and Systems by Cindy Sridharan.

**Comment by TangoYankee** [comment]
I vote to move to implementing.

**Comment by hawser** [comment]
I also vote to move to implementing.

**Comment by kiwisquash** [comment]
@TangoYankee, I'm not 100% sure where the proposed text is meant to go. Should it come after the first sentence in the *Issues* section?

**Comment by theecrit** [comment]
@kiwisquash Good point; it feels a little heavy-handed dropped into the doc. How about we edit it way down and make it part of the **Issues** section:

> Issues are the primary means of coordinating code implementation. We use issue comments to explicitly document implementation discussions and decision-making. This allows us to vet our individual assumptions, clarify a shared mental model of the code, outline pseudo-code and other solutions, and pair program. It also documents the design process for future developers. [[More Context]](https://medium.com/@copyconstruct/effective-mental-models-for-code-and-systems-7c55918f1b3e)

> Issues will have one of four status labels...

**Comment by kiwisquash** [comment]
Closing the issue since the merge is complete.
