### ISSUE TITLE
As a user, I want to be able to sign into my account.

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#71]
**This issue covers the following features/flows**
- Account sign-in user interface (html template and CSS/JS styling)
  - Backend is already handled by Django built-in functionality
- Account creation
  - "Account creation" should be changed to read "contact [insert email address] to request an account"
  - It should be plain text, rather than a hyperlink 
- Password hide/reveal
  - See note below

**Not in this issue's scope***
- Password reset / `Forgot Password` link
- Footer
- `Visit WOEIP` link

**Notes on "Sign In" button**
- Ignore the "inactive state" in the wireframes.

**Notes on password hide/reveal**
- Password field on sign-in form to default to obscuring the characters as they're entered.
- Visual indicator/toggle to reveal characters (either eye icon right-aligned within input field, or a text label reading "Show", that changes to "Hide" on reveal).

**Additional context**
~n/a~
Edit: This is an enhancement to the built-in Django Form. - Tim

### For Developers
**Affected Components**
The login template and any CSS and/or JS needed to style it

**Technical Resources**
[Django Forms](https://docs.djangoproject.com/en/2.1/topics/forms/) will need to be modified with css classes from Foundation
~~[Zurb Foundation Show Password](https://foundation.zurb.com/building-blocks/blocks/show-password.html)~~
[W3 Schools Javascript Simple Reveal](https://www.w3schools.com/howto/howto_js_toggle_password.asp)
- [Forms Example](https://docs.djangoproject.com/en/dev/topics/auth/default/#module-django.contrib.auth.views)

**Design Documentation**
[WOAQ-Wires-PasswordReveal-20180326.pdf](https://github.com/openoakland/woeip/files/3011419/WOAQ-Wires-PasswordReveal-20180326.pdf)

**Comment by theecrit** [comment]
Interesting [article from Luke Wroblewski](https://www.lukew.com/ff/entry.asp?1941/) on defaulting to show password, with [backup from Nielsen Norman](https://www.nngroup.com/articles/stop-password-masking/). I'm not married to either approach, but seems that defaulting to show password, with an option to hide, is more low-computer-skills friendly. And since security is not a primary part of the UX here, my inclination would be to default to making it easier for the user.

Then I did a survey of what people are actually doing, look at 14 sites (half of which were e-comm sites graded "acceptable" or higher for account sign-in usability from Baymard.com, half of which were other sites known for their focus on UX): [Google Sheet comparison](https://docs.google.com/spreadsheets/d/1rHOAen3edSN_HoeYXHaoEKD7sUBmRFAhViftthFxri8/edit?usp=sharing) • [Visuals](https://github.com/openoakland/woeip/files/3010961/PatternAnalysis-AccountSignIn.pdf)

All but one of the sites hides the password on default, and half of those *don't offer any way to show the password characters at all*, which feels *really* unfriendly to me. I'd love to hear others' thoughts on this.

**Comment by TangoYankee** [comment]
@theecrit I think hiding the password on default and then offering to show it is a good compromise between security and friendliness.

**Comment by TangoYankee** [comment]
I also wouldn't object to making this issue encompass the whole sign in page front end. It seems we have the wireframes for it.

**Comment by theecrit** [comment]
@TangoYankee Would it make sense to combine it with https://github.com/openoakland/woeip/issues/23?

**Comment by theecrit** [comment]
@TangoYankee Can you review and re-label this as `ready` if you concur?

**Comment by TangoYankee** [comment]
@theecrit Django defaults to logging in with username, rather than email. I'm not sure whether this makes a significant difference for you. I'm proceeding with username. Let me know if you want an issue to convert the login to email.

**Comment by theecrit** [comment]
I worry that username adds a level of complexity to a flow that's already something of a blocker/gate to the primary experience. It's another thing for CM and her team to have to remember, and she's already given us feedback in multiple instances that additional memorization can be tough on her ability to complete a given flow (she requires a lot of repetition and visual/text reference/prompts to be able to get through a flow of any complexity).

If it's fairly low overhead to override the default and allow sign-in with email, I do think that's significantly preferable.

**Comment by TangoYankee** [comment]
Overwriting the email should be straightforward. For the scope of this issue, let's keep username. I'll open another issue to swap username for email, before MVP.
