### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#74]
**Is your feature request related to a problem? Please describe.**
Create a navigation bar for users to find top-level pages.

**Describe the solution you'd like**
A top bar menu that transforms into a hamburger menu on smaller screens.

**Describe alternatives you've considered**
A list of links and their descriptions in the body of the homepage. This may provide context for new users. However, it goes against established best practices. Additionally, it would require users to navigate back to the homepage to find any other page. 

**Additional context**
The majority of users should interact via the desktop site. However, we should accommodate mobile users.

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
- Top-level links are currently housed in the `_header.html` file, under the `includes` directory.
They should be moved a dedicated file named `_navigation.html`, still within the `includes` directory. 
- Also part of this issue, please refactor `_header.html` to `_messages.html`, as that is all this file will contain. 
- Within `__base.html` "include" `includes/_navigation.html` just below the `<body>` tag, above `includes/_header.html`
- Refactor `includes/_header.html` to `includes/_messages.html`

**Technical Resources**
[Django Template Structuring Convention](https://oncampus.oberlin.edu/webteam/2012/09/architecture-django-templates)
[Zurb Responsive Header](https://foundation.zurb.com/sites/docs/responsive-navigation.html)

**Design Documentation**

Reference pages using their names: ie) `"{% url 'index' %}"`, to make it easier to refactor later

Links in the navigation bar:
- 'Brand' link should float left and be displayed on all screen sizes
  - **WOAQ**, name: 'index' (Displayed to all users)
- 'List' links should float right on larger screens and turn into a right-sided hamburger menu on smaller screens. From left to right, they are:
  - **Add Data**, name `upload` (Displayed to all users.)
    - Only logged in users can upload data. However, always displaying it allows users to understand their options. 
  - ~**Log in**~ **Sign In**, name `login` (Displayed only if user is logged out)
  - ~**Log out**~ **Sign Out**, name `logout` (Displayed only if user is logged in)
  - **View Maps**, links to `#` until page is built
  - More links (such as Sessions) will be added, as the site grows.
  - Remove the `Request Account` link

Edit: Updated links based on wireframes

Wireframes or other design resources
[Nav Bar Wires](https://trello.com/c/7QiIwJbT/89-nav-bar-wires)
Prototype Branch: [ty/toggle-navigation](https://github.com/openoakland/woeip/tree/ty/toggle-navigation)
[WOAQ-Wires-Nav-20190325.pdf](https://github.com/openoakland/woeip/files/3005987/WOAQ-Wires-Nav-20190325.pdf)

**Comment by TangoYankee** [comment]
Incorrectly loaded Foundation Javascript CDN and custom javascript app.
- Missing `%` in `static app.js`
- Missing scripts and stylesheets
  - [Correct Load method](https://gist.github.com/Yogatopia/2c5c8b9b6f3ec08908ee)

**Comment by theecrit** [comment]
Wireframes attached: [WOAQ-Wires-Nav-20190325.pdf](https://github.com/openoakland/woeip/files/3005987/WOAQ-Wires-Nav-20190325.pdf)

**Comment by TangoYankee** [comment]
@theecrit Want a hamburger menu for mobile? I hope you say yes because I already figured it out.

**Comment by TangoYankee** [comment]
Hamburger menu for MVP. We'll user test and iterate as the site develops.

**Comment by theecrit** [comment]
@nbilenko Should I re-label this as `implementing`?

**Comment by nbilenko** [comment]
Here's a branch: [nb/nav-bar](https://github.com/openoakland/woeip/tree/nb/nav-bar), building on the prototype branch + added styling based on wireframe and accessibility features.
Can I open a pull request at this stage?

**Comment by TangoYankee** [comment]
I looked it over. Smells good to me. I opened the PR myself because I was curious as to how git would handle the different versions of the Docker file- python:3.6 is now the official base image. 

Of course, now we're in the awkward position where it's your code. But, ... I can't review it and you can. Whoops.

Anyway, add your review and approve the changes when you see fit. I'll leave the PR open for the 36hrs. That way, the rest of the team can add their opinions.

**Comment by nbilenko** [comment]
Cool, I added a comment but it doesn't let me approve (maybe b/c I'm not under "approving reviewers").

**Comment by TangoYankee** [comment]
Modified the header so that it says 'West Oakland Air Quality' in the top bar, without needing a dropdown. Branch [ty/responsive-header](https://github.com/openoakland/woeip/tree/ty/responsive-header)

![WOAQ Responsive Header](https://user-images.githubusercontent.com/11068062/60559702-294e3f00-9d02-11e9-8ffe-eb21b09b35be.png)

**Comment by nbilenko** [comment]
Closing this issue b/c it's no longer relevant.
