### ISSUE TITLE
As a user, I want my starting point to be the sign-in page

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#76]
**Is your feature request related to a problem? Please describe.**
The user needs a starting URL to begin their experience.

**Describe the solution you'd like**
Redirect /index to /signin (I'd prefer to use "sign in" language consistently over "log in" because it's more user-centric, as opposed to system-centric). 

**Describe alternatives you've considered**
The resources to scope, design, and implement a proper home page at /index is better used for core MVP functionality. 

**Additional context**
We've got a [backlogged issue](https://github.com/openoakland/woeip/issues/34) for the /index landing page once MVP has shipped. This will also buy us time to finalize some of the open questions around project positioning and team roles.

**Edit:** `Sign in` already redirects to `index`. If we have `index` redirect to `signin`, then it will be an endless circle. Alternatively, we could redirect from `index` to `upload`. If the user is logged in, they continue seemlessly to `add data`. If they are not signed in, they are gracefully redirected to the sign in page. Once signed in, they are advanced to the `upload` page. This is bad django. But, it's good UX. We'll pay for our sins, after MVP. Changes are updated in the **Technical Resources** Section
-Tim

### For Developers
**Affected Components**
`air_quality/views.py` `index` function

**Technical Resources**
- The index view should `return redirect ('upload')` ~~`redirect('[insert name of sign in page]')`~~
- Alternative approach from simple is better than complex [Django Login Views](https://simpleisbetterthancomplex.com/tutorial/2016/06/27/how-to-use-djangos-built-in-login-system.html)
- [StackOverFlow](https://stackoverflow.com/questions/20208562/homepage-login-form-django#20210318)
**Design Documentation**
TBD

**Comment by TangoYankee** [comment]
I swapped the tags. If I'm not mistaken, the landing page is **backlog** but this redirect is **MVP**. Also, I think it's ready from implementation.

**Comment by theecrit** [comment]
@TangoYankee When you say we have /signin redirecting to /index, do you mean once the user is signed in, they are redirected to /index?

**Comment by TangoYankee** [comment]
> @TangoYankee When you say we have /signin redirecting to /index, do you mean once the user is signed in, they are redirected to /index?

Currently, yes. However, if they originally asked to go to `add data` but are stopped by the `signin` page, then signing in will redirect them to `add data`. That's the behavior I'm going for, by have `index` redirect to `add data`. If I'm not mistaken, that's the original flow you designed.

**Comment by TangoYankee** [comment]
@r-b-g-b On the next iteration, we could look into nginx handling the redirect, instead of Django. Although, I don't think it's worth the research time for the MVP.

**Comment by TangoYankee** [comment]
I made two versions of this solution. The first version is [ty/upload-as-home](https://github.com/openoakland/woeip/tree/ty/upload-as-home). This is pull request #85 . It's the simplest solution. Also, when a user is already authenticated, then it will redirect to the upload page. The second version is [ty/login-as-home](https://github.com/openoakland/woeip/tree/ty/login-as-home). It modifies the `LoginView` url to control `/`. Unfortunately, even authenticated users will be brought to the login screen, when returning to the website.
