### ISSUE TITLE
As a WOAQ team member, I want a single public contact option with multiple fallbacks.

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#84]
**Is your feature request related to a problem? Please describe.**
Currently, there's no direct contact info in the ReadMe doc, other than for reporting security issues, and that directs people directly to Tim's email address. This poses two problems:
- Visitors don't know how to reach WOAQ for general inquiries.
- Only one person is alerted of security issues, which means if that person is unavailable the security issue may go unaddressed in a timely fashion.

We now have a general email address that forwards to both Jess and Tim, so two people will always be notified of any security issues or incoming communication.

**Describe the solution you'd like**
- Under "Reporting Security Issues," replace "Instead, please contact Tim Miller at miller.tim108@gmail.com" with "Instead, please send an email to the WOAQ team at: [woaq@openoakland.org](mailto:woaq@openoakland.org)."
- Below that, add a section titled "Contact Info" with the following instruction: "For general inquiries about the project, email us at [woaq@openoakland.org](mailto:woaq@openoakland.org). Or come visit us on [Tuesday evenings at City Hall](https://www.meetup.com/OpenOakland/)."

**Describe alternatives you've considered**
Leaving Tim's email as-is, but that poses potential security issues. 

**Additional context**

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
[ReadMe.rst](https://github.com/openoakland/woeip/blob/master/README.rst)

**Technical Resources**
Add links to appropriate documentation. Describe possible code implementations.

**Design Documentation**
Wireframes or other design resources

**Comment by TangoYankee** [comment]
Vote to implement

**Comment by TangoYankee** [comment]
I'll combine this with the testing documentation issue (#83). The contributing document also includes a reference to my email for security issues. I'll be editing the contributing doc for that issue anyway. I think these are small enough issues that we can combine them.
