### ISSUE TITLE
Styling and Accessibility for Verification Page (3/3)

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#89]
**Is your feature request related to a problem? Please describe.**
A page where users can view, verify, and edit the meta data that was automatically generated for the session.

**Describe the solution you'd like**
The user should be brought to a page where they are presented with a form, pre-filled with data. The user can change the values of the data in the fields. The user can either save the data or cancel the upload. Saving progresses to the session view page. Canceling returns the user to the upload page.

**Describe alternatives you've considered**
Manually entering all fields, when initially uploading data.

**Additional context**
This issue is only a basic, first pass at accessibility and responsive design

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
This issue is one of three dealing with the verification page. The three issues will create a skeleton of the necessary components, fill the skeleton with data from the S3 bucket and Staging Table or handle errors, and finally add styling & accessibility to the page.

This issue adds responsive styling and basic accessibility to the page:
- HTML template (tagging and linking tags to style classes)
- app.css (Referenced in a way that localizes the changes)
- app.js

**Technical Resources**
[Django Templating Style](https://oncampus.oberlin.edu/webteam/2012/09/architecture-django-templates)

**Design Documentation**
[WOAQ Approach to Accessibiliy](https://trello.com/c/zfsYqv5H/84-as-a-woaq-team-member-i-want-to-understand-our-approach-to-accessibility)
[Wireframes](https://github.com/openoakland/woeip/files/2959738/WOEIP-UploadFlow-v3.pdf)

**Testing**
To be determined

**Comment by theecrit** [comment]
Blocked until Upload flow is implemented.

**Comment by theecrit** [comment]
@TangoYankee @ifed3 If we end up moving to a React front-end, this issue would need to be closed and addressed as part of the larger design system, correct?

**Comment by theecrit** [comment]
Closing as "won't fix" - will be covered by other issues TBD.
