### ISSUE TITLE
Integrate data into verification page and handle errors (2/3)

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#90]
**Is your feature request related to a problem? Please describe.**
A page where users can view, verify, and edit the meta data that was automatically generated for the session.

**Describe the solution you'd like**
The user should be brought to a page where they are presented with a form, pre-filled with data. The user can change the values of the data in the fields. The user can either save the data or cancel the upload. Saving progresses to the session view page. Canceling returns the user to the upload page.

Login is required for this view

**Describe alternatives you've considered**
Manually entering all fields, when initially uploading data.

**Additional context**
Data is coming from an S3 bucket and a staging table. Only the meta-data is extracted and verified. After user confirmation of the meta-data, all of the air quality and its metadata are saved to the SQL database.

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
This issue is one of three dealing with the verification page. The three issues will create a skeleton of the necessary components, fill the skeleton with data from the S3 bucket and Staging Table or handle errors, and finally add styling & accessibility to the page.

This issue integrates the data from the Staging table, handles extensive errors, and "prepares" the data for the SQL Database (Actual upload of the data to SQL is the next issue).

Affected components:
- Staging Table
- View
- View test (including integration of staged data)
- Error Handling (Including loss of internet connection, failure of web browser, or accidental early navigation away from page)

**Technical Resources**
TBD

**Design Documentation**
[Wireframes](https://github.com/openoakland/woeip/files/2959738/WOEIP-UploadFlow-v3.pdf)
[Status of Data Trello Card](https://trello.com/c/0ZEkmsRk/90-status-of-data-during-verification-step)

**Testing Resources**
[Django Testing](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing)

**Comment by theecrit** [comment]
@TangoYankee Can you confirm the following relationships?

- **[31. As a user, I would like to drag and drop my gps and dustrak files to upload them](https://github.com/openoakland/woeip/issues/31):** Drop zone front-end for #81 
- **[81. As a user, I want to upload air quality and location data to the website](https://github.com/openoakland/woeip/issues/81):** Comments suggest this is back-end logic required for #31, but Issue description suggests the focus is meant to be the file-selection-from-local-drive front-end. I feel like the back-end logic piece belongs to one of these other Issues (perhaps 43)?
- **[43. As a user, I would like the website to automatically know about my data](https://github.com/openoakland/woeip/issues/43):** Back-end data extraction from uploaded files, required for #31 
- **[63. As a data uploader, I want to verify the information I've uploaded to the system](https://github.com/openoakland/woeip/issues/63):** Now covered by issues #88, #89, and #90 (therefore #63 should be closed, correct?)

Thanks!

**Comment by TangoYankee** [comment]
Yes. I added a few labels because I wrote many of them and even I'm confused by their relationships.

For #81, it focuses on the selection from local drive because that is the backend basis for the drag and drop frontend (unless my assumption is wrong). Also, the wireframes indicated that we still want to have a 'select from file explorer' backup to the drag and drop.

**Comment by theecrit** [comment]
Upload is blocking this.

**Comment by theecrit** [comment]
@TangoYankee Don't forget about #63

**Comment by theecrit** [comment]
Closing as "won't fix" due to changes in tech stack; now covered in issue #132.
