### ISSUE TITLE
As a user, I need to manage my password (1/2)

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#96]
**Is your feature request related to a problem? Please describe.**
An ability to reset forgotten password. There is also a need to change the password originally set by the developer that created the account. 

**Describe the solution you'd like**
Reset the password using the default django forms and email workflow

**Describe alternatives you've considered**
A magic login link. This flow is not as well established and not supported from django, "out of the box"

**Additional context**
Will require an integration with an email server. This is the second issue associated with password reset. This issue will send "emails" to a folder.

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [x] Add additional labels as needed

### For Developers
**Affected Components**
- html templates
- urls
- account from which to send email
  - woaq@openoakland.org
  - protect login credentials

**Technical Resources**
[Will Vincent Tutorial](https://wsvincent.com/django-user-authentication-tutorial-password-reset/)
[Simple is better than complex tutorial](https://github.com/openoakland/woeip/pull/87#discussion_r278317244)
[Django Send Email](https://docs.djangoproject.com/en/2.2/topics/email/)
[Django Auth Documentation](https://docs.djangoproject.com/en/2.2/topics/auth/default/#module-django.contrib.auth.views)

**Design Documentation**
- Grid structuring of elements, similar to signin page
- Stock Foundation styling
- Stock Django templates and views

**Testing Outline**
- Using stock Django. Minimal integration testing required.

**Comment by TangoYankee** [comment]
@theecrit In addition to resetting a password, users need a way to change their password. That's also part of the stock Django. The question is... where do we put the `change my password` link. 

Usually, we would put it on the user's profile. But, we don't have one of those. I'm thinking the nav bar is the best place for it now.

**Comment by TangoYankee** [comment]
The domain in the `password_reset_email.html` template is currently hard-coded with `localhost:8080`. I opened issue #98 to fix that, in a new pull request.

**Comment by theecrit** [comment]
> Usually, we would put it on the user's profile. But, we don't have one of those. I'm thinking the nav bar is the best place for it now.

I'd been thinking about this a bit already (account creation begs the question of account management). I *think* nav bar is ok for now but I have a card for addressing it within the larger question of IA: https://trello.com/c/MecWIQg8

Language will also need to be thoughtful (e.g. "My Account" vs "Reset Password" vs. something else).

**Comment by TangoYankee** [comment]
The code is in PR #100. The nav bar when signed in looks like:

![WOAQ Change Password 2019-04-25 17-11-15](https://user-images.githubusercontent.com/11068062/56775757-5e2b9c00-677d-11e9-838e-bb00920eb46c.png)

**Comment by theecrit** [comment]
Let's keep capitalization consistent in the nav and use sentence case (only letter of first word of phrase is capitalized):

- Add data
- View maps
- Change password
- Sign out

**Comment by TangoYankee** [comment]
> Let's keep capitalization consistent in the nav and use sentence case (only letter of first word of phrase is capitalized):
> 
> * Add data
> * View maps
> * Change password
> * Sign out

Changed

**Comment by TangoYankee** [comment]
PR #100
