### ISSUE TITLE
As a developer, I would like to send emails programmatically to reset user passwords (2/2)

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#97]
**Is your feature request related to a problem? Please describe.**
Users will be sent emails to with email reset passwords

**Describe the solution you'd like**
These emails should be sent with a service, such as SendGrid, MailGun or Mandrill.

**Additional context**
This is the second issue related to password reset. The first issue implements a development backend to store emails in a local folder. This issue implements a production-ready email service

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [ ] Add additional labels as needed

### For Developers
**Affected Components**
- settings.py email service
- password management for woaq email account

**Technical Resources**
- [Email service tutorial using SendGrid](https://simpleisbetterthancomplex.com/tutorial/2016/06/13/how-to-send-email.html)
- Mailgun is being used for some existing OO projects, though not tied to an official OO account. While we do have a woaq@openoakland.org email that can be used to create a Mailgun (or SendGrid et al) account, OpenOakland would prefer to keep services centralized if possible. That means using services@openoakland.org to set up any new accounts for this. That email goes to members of the steering comimittee; if email access is needed to verify a new account or whatnot, contact Tom Dooner (@tdooner), Mike Ubell (@mikeubell), or Alison Lawyer (@anlawyer). If this ends up being a blocker, we may need to switch to using the woaq@openoakland.com address.

**Design Documentation**
Wireframes or other design resources

**Testing Outline**
Describe the testing methods appropriate for this feature

**Comment by theecrit** [comment]
Can we add a note to include due diligence around security issues for this particular feature?

And by extension, is it worth opening a new Issue to specifically do due diligence around security requirements as a whole? I think it’s worth treating it as intentionally as a11y.

**Comment by TangoYankee** [comment]
These are all well-tread methods. The due diligence on this topic is basically "don't screw up the configurations or accidentally commit your credentials to github"

"Security requirements" is a broad topic and doesn't really lend itself to an issue. It would be better discussed in the format of a trello card and/or google doc.

**Comment by theecrit** [comment]
Sure thing. Here's a broad card for the overarching question of "security and safety": https://trello.com/c/Er8vSgAS

And a card specific to addressing the security of users' personally-identifiable information: https://trello.com/c/pIS902jc

**Comment by theecrit** [comment]
Current blocker is choosing a service. I'm going to reach out to OO and see if they have existing recs/accounts.

**Comment by theecrit** [comment]
Rolled into #147
