### ISSUE TITLE
Manage the django sites domain

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woeip#98]
**Is your feature request related to a problem? Please describe.**
Django has a `domain` variable, set when using the [sites framework](https://docs.djangoproject.com/en/dev/ref/contrib/sites/). By default, it is set to `example.com`. When sending password reset emails, the email template references the `domain` variable. It needs to be set, so that users are directed to the correct domain.

**Describe the solution you'd like**
Configure the site values to easily change between `[local]:[port]` for testing and `woaq.org` for production

**Describe alternatives you've considered**
Keeping the domain variables hard-coded in all their references

**Additional context**
The domain in the `password_reset_email.html` is currently hard-coded with `localhost:8080`. It will need be changed to `woaq.org`

**Labels**
- [x] Add a status label
  - `backlog`
  - `discussing`
  - `ready`
  - `implementing`
- [ ] Add additional labels as needed

### For Developers
**Affected Components**
- `settings.py`
- `password_reset_email.html` domain
- See also #116 

**Technical Resources**
[Sites framework](https://docs.djangoproject.com/en/dev/ref/contrib/sites/)

**Design Documentation**
Wireframes or other design resources

**Testing Outline**
Describe the testing methods appropriate for this feature

**Comment by TangoYankee** [comment]
@theecrit The aspect of choosing a production domain should probably be a Trello card?

**Comment by theecrit** [comment]
Done: https://trello.com/c/oP90jpQW

**Comment by theecrit** [comment]
Do we want to re-map this to use woaq.org once that's secured?

**Comment by theecrit** [comment]
@TangoYankee Does this issue seem sufficiently detailed to relabel as `Ready`? If so, I'll update.

**Comment by theecrit** [comment]
Closing.
